### ISSUE TITLE
where can I find kitti disparity map

### ISSUE THREAD

**Issue by wlgcqh** [mrharicot/monodepth#1]

**Comment by mrharicot** [comment]
Hi,

Which disparities are you looking for?

-Clement

**Comment by wlgcqh** [comment]
`disp = cv2.imread(path + "/training/disp_noc_0/" + str(i).zfill(6) + "_10.png", -1)` in utils/evaluation_utils.py 38 lines,I'm looking for kitti disparity map ground truth.

**Comment by mrharicot** [comment]
They are the [KITTI 2015 stereo disparities](http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo), you can find them here:
http://www.cvlibs.net/download.php?file=data_scene_flow.zip

-Clement

**Comment by wlgcqh** [comment]
thanks a lot for your response! it's a fantastic work in this year

**Comment by salmankh47** [comment]
@mrharicot How can I convert sparse disparity map to dense? 
The disparity provided in scene_flow dataset looks sparse.

![sparse_disp](https://user-images.githubusercontent.com/11402696/55621552-77af7880-57bb-11e9-8b3c-200945f2f9f7.png)

**Comment by 1475015695** [comment]
> @mrharicot How can I convert sparse disparity map to dense?
> The disparity provided in scene_flow dataset looks sparse.
> 
> ![sparse_disp](https://user-images.githubusercontent.com/11402696/55621552-77af7880-57bb-11e9-8b3c-200945f2f9f7.png)

Did you soved it?I met the same issue

**Comment by royshil** [comment]
you could use maxpooling to dense up the sparse map in expense of resolution
```
kittiD = cv2.imread('training/disp_noc_0/000000_10.png',0)
import skimage.measure
plt.imshow(skimage.measure.block_reduce(kittiD, (5,5), np.max))
```
![image](https://user-images.githubusercontent.com/441170/127694910-5748fb16-b840-4ea0-a0e8-ac9377ff3a20.png)
