### ISSUE TITLE
disparity format

### ISSUE THREAD

**Issue by parhartanvir** [mrharicot/monodepth#10]
I just want to use the function in **bilinear_sampler.py**. in what format does it require the images and the disparity map to be in? 

To elaborate :- Should it be in a range of 0-255, where 255 is max disparity, of just in terms of pixel disparity values, or scaled between 0-1

Thank you

**Comment by mrharicot** [comment]
Hi,

The bilinear sampler expects disparities to be between -1 and 1, they are then scaled by the width of the image in the function.
The disparities can be larger, but will then fetch outside of the bounds of the image all the time.

**Comment by parhartanvir** [comment]
All right!,
Thanks
