### ISSUE TITLE
Training without Rectified Images

### ISSUE THREAD

**Issue by Optimus1072** [mrharicot/monodepth#100]
It is a question rather than a issue.
Did you try training the model without rectifying the images. I agree that rectifying will make it easier for the model to find the mapping function, but getting similar results without doing rectification will surely open doors for many applications.

**Comment by mrharicot** [comment]
Hi,
Good question!
It is entirely possible to do it with non rectified images, however it requires to backproject points into 3d and then project into the other view.
This requires to know intrinsics + extrinsics.
You can have a look at Zhou et al.'s work: https://people.eecs.berkeley.edu/~tinghuiz/projects/SfMLearner/

**Comment by Optimus1072** [comment]
Thanks for such a quick reply, I'll go through the paper and will get back to you. What I understand from the abstract is that  we need to transform both left and right images to some common plane which reduces the search dimension(same as we do in rectification) and hence the knowledge of intrinsics and extrinsics(which again is required in rectification). Am I correct?

Further,  one more question that is not related to this topic.What was the final loss value that you achieved  when you trained with KITTI dataset?

**Comment by mrharicot** [comment]
In this work they trained two networks: one learns to find the transformation between two images.
The second network learns depth so that when using the predicted transformation, the first image reprojects into the second one.

**Comment by Optimus1072** [comment]
Thanks :-)
