### ISSUE TITLE
About cudnn and python version, you have used

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#102]
Hi, I am wondering that which version of cudnn and python were you using for this project?
Previously, I used cudnn v6 with newest tensorflow version1.4, but my computer froze when I ran the program. Yesterday, I tried to use cudnn v5.1 with older version of tensorflow0.12 which is working fine right now.  
Could you provide the detail to set up the environment? Thank you.

**Comment by mrharicot** [comment]
Hi,
I have tested the code under python 2.7 with all the TF versions since 1.0, the corresponding latest CUDA and cudnn all under Ubuntu 16.04.
Problems with cuda and cudnn are fairly common, make sure your drivers are up to date and you have the correct version of cuda for your cudnn.

**Comment by keishatsai** [comment]
Thanks for suggestion! I am sure that my driver is up to date (which is nvidia-384), and CUDA is 8.0 with cudnn v6 under Ubuntu 16.04. Currently, I am trying to train model on Tensorflow1.4 now, and hope that it won't crash again.

**Comment by keishatsai** [comment]
Looks like it is working fine right now, so I close this issue.
Thanks for the help!!!
