### ISSUE TITLE
Get memory error while training on Cityscapes, does it affect the performance, if I lower the batch size?

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#103]
Hello, I just confused by this error when I try to train the Cityscapes dataset. Can anyone help me to solve this problem?
thank you
I currently use Tensorflow 1.0 , CUDA 8.0 and cudnn5.1.  Nvidia Geforce GTX 970 

`python monodepth_main.py --mode train --encoder resnet50 --model_name model20180130 --data_path ~/wonderland/datasets/cityscapes/training_cityscapes/ --filenames_file ~/wonderland/paper_code/monodepth-master/utils/filenames/cityscapes_train_files.txt --log_directory ~/wonderland/monodepth-tmp/model20180130`

total number of samples: 22973
total number of steps: 143600
/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
number of trainable parameters: 58452008
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.16GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.13GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.17GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 3.28GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 882.00MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.12GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 648.00MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 576.00MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 4.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,256,512,1]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 3.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,128,256,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 4.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 4.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 8.00MiB.  See logs for memory state.
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 8.00MiB.  See logs for memory state.
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 3.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,128,256,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 4.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,256,512,1]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 12.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,256,512,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 4.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,256,512,1]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.93MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,126,254,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.96MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.93MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,126,254,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 1.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,128,256,1]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 11.86MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,254,510,3]
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************x***********************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 12.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,256,512,3]
Traceback (most recent call last):
  File "monodepth_main.py", line 331, in <module>
    tf.app.run()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 326, in main
    train(params)
  File "monodepth_main.py", line 168, in train
    _, loss_value = sess.run([apply_gradient_op, total_loss])
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
	 [[Node: gradients/model/encoder/Conv_52/BiasAdd_grad/tuple/control_dependency_1/_1641 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_11418_gradients/model/encoder/Conv_52/BiasAdd_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'gradients/losses/pow_28_grad/Log', defined at:
  File "monodepth_main.py", line 331, in <module>
    tf.app.run()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 326, in main
    train(params)
  File "monodepth_main.py", line 122, in train
    grads = opt_step.compute_gradients(loss)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 354, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 482, in gradients
    in_grads = grad_fn(op, *out_grads)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py", line 686, in _PowGrad
    log_x = array_ops.where(x > 0, math_ops.log(x), array_ops.zeros_like(x))
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1345, in log
    result = _op_def_lib.apply_op("Log", x=x, name=name)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'losses/pow_28', defined at:
  File "monodepth_main.py", line 331, in <module>
    tf.app.run()
[elided 1 identical lines from previous traceback]
  File "monodepth_main.py", line 326, in main
    train(params)
  File "monodepth_main.py", line 115, in train
    model = MonodepthModel(params, args.mode, left_splits[i], right_splits[i], reuse_variables, i)
  File "/home/keisha_tsai/wonderland/paper_code/monodepth-master/monodepth_model.py", line 56, in __init__
    self.build_losses()
  File "/home/keisha_tsai/wonderland/paper_code/monodepth-master/monodepth_model.py", line 359, in build_losses
    self.ssim_right = [self.SSIM(self.right_est[i], self.right_pyramid[i]) for i in range(4)]
  File "/home/keisha_tsai/wonderland/paper_code/monodepth-master/monodepth_model.py", line 103, in SSIM
    SSIM_d = (mu_x ** 2 + mu_y ** 2 + C1) * (sigma_x + sigma_y + C2)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 571, in pow
    return gen_math_ops._pow(x, y, name=name)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1717, in _pow
    result = _op_def_lib.apply_op("Pow", x=x, y=y, name=name)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,254,510,3]
	 [[Node: gradients/losses/pow_28_grad/Log = Log[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](losses/AvgPool2D_20/AvgPool)]]
	 [[Node: gradients/model/encoder/Conv_52/BiasAdd_grad/tuple/control_dependency_1/_1641 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_11418_gradients/model/encoder/Conv_52/BiasAdd_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by keishatsai** [comment]
I simply change the batch size from default 8 to 4, and the program can be run. 
However, does this change the final performance? I doubt.

**Comment by mrharicot** [comment]
Hi,
It might change the performance a bit, unclear in what way.
We didn't do much experimenting with the batch size.

**Comment by keishatsai** [comment]
Thanks for the reply. I will try to figure it out.

**Comment by keishatsai** [comment]
After I add the flag `--encoder resent50`, and the program finally ran.
However, the result wasn't that good, while I  test one of image from Cityscapes.
Original:
![cityscapes_munich_000021_000019_leftimg8bit](https://user-images.githubusercontent.com/8175070/35714656-07f301c2-0809-11e8-84eb-97df5bb58be7.png)
Result:
![0_disp](https://user-images.githubusercontent.com/8175070/35714649-fe23b236-0808-11e8-9654-1de169c52088.png)
