### ISSUE TITLE
get_model.sh 404 Not Found

### ISSUE THREAD

**Issue by SsaRu** [mrharicot/monodepth#108]
Hello, i was trying get resnet pretrained model 
but i get error "404 Not Found" 
it seems to blocked or disappeared that web site
how i can solved?
Thanks

**Comment by keishatsai** [comment]
Hello~~I think you can visit the project website below:
http://visual.cs.ucl.ac.uk/pubs/monoDepth/
There is a link to the Model files. Hope this helps you :)

**Comment by SsaRu** [comment]
it's very clear and helpful
Thanks about quickly answer

have a nice day!
