### ISSUE TITLE
[In monodepth_simple.py] How do you generate depth map instead of knowing focal length and the baseline

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#109]
Hello, 
Currently, I am working on training on my own data.
I am curious about that how do you generate depth map instead of knowing focal length and the baseline in monodepth_simple.py

I am using the disparities file (which generated from monodepth_simple.py) with define focal length and baseline, but the image I calculated is not right. However, the output from monodepth_simple.py is way better.

**Comment by mrharicot** [comment]
Hi,
Could you give a bit more information?
What is not right about the disparities in one monodepth_simple case, what parameters did you run it with?

If you don't know the focal length nor the focal you will only have relative depth. which differs from metric depth by a scale, you could try to eyeball it or measure something in the image which you know the size of.

**Comment by keishatsai** [comment]
Hi, @mrharicot 
sorry for not providing detail.
I tried to use disparity generated from monodepth_simple.py.
focal length: 27.5cm
baseline: 6.5cm
Here are my steps to convert the disparity to depth image.
>>> mat = np.load('frame-003325_disp.npy')
>>> mat.max()
0.04439399
>>> mat.min()
0.00033407987
>>> mat.squeeze().astype(np.float32)/ 256
array([[2.96438648e-05, 3.70917260e-05, 3.11938347e-05, ...,
        1.33085105e-05, 1.84990622e-05, 1.42607159e-05],
       [6.57995188e-05, 3.64692642e-05, 5.72057106e-05, ...,
        2.41224243e-05, 1.68622246e-05, 3.18871244e-05],
       [3.74441988e-05, 3.69120971e-05, 5.07449840e-05, ...,
        2.09490881e-05, 1.72933323e-05, 1.70991843e-05],
       ...,
       [7.50381878e-05, 9.99449330e-05, 1.14856470e-04, ...,
        1.51305256e-04, 1.28198837e-04, 9.91879861e-05],
       [7.93225045e-05, 9.81122575e-05, 1.08557702e-04, ...,
        1.48227657e-04, 1.23121281e-04, 9.13897093e-05],
       [9.34020427e-05, 9.53641211e-05, 1.03133534e-04, ...,
        1.33415568e-04, 1.19740107e-04, 1.16340663e-04]], dtype=float32)
>>> pre_depth = 27.5 * 6.5 /mat
>>> print(pre_depth)
[[23554.357  18824.742  22383.98   ... 52465.84   37744.734  48962.633 ]
 [10611.661  19146.045  12205.8125 ... 28945.771  41408.664  21897.309 ]
 [18647.54   18916.352  13759.827  ... 33330.434  40376.383  40834.824 ]
 ...
 [ 9305.158   6986.269   6079.259  ...  4614.7915  5446.556   7039.5845]
 [ 8802.573   7116.768   6431.991  ...  4710.6064  5671.174   7640.2715]
 [ 7475.663   7321.854   6770.273  ...  5233.5884  5831.314   6001.7036]]
>>> 
>>> disp_to_img = scipy.misc.imresize(pre_depth,[512,640])
>>> plt.imsave('new_test.png',disp_to_img, cmap='plasma')
The image directly from monodepth_simple.py:
![frame-003325_disp1](https://user-images.githubusercontent.com/8175070/36074803-72347b00-0f80-11e8-967e-fb216a3d4ddd.png)
The image I generated from the disparities file which from monodepth_simple and follow the steps I write above.
![new_test](https://user-images.githubusercontent.com/8175070/36074847-f0f8c9fa-0f80-11e8-866b-f7ba377d6fb4.png)

**Comment by mrharicot** [comment]
Hi,
The focal should be expressed in pixels, not cm.
You can also reduce the maximum depth by doing:
depth = focal * baseline / (disparity + 1/max_depth)
It will very so slightly bias all your results but will limit the maximum depth.

**Comment by keishatsai** [comment]
Hi, thank you for the advice, but what do you mean that the focal length should be expressed in pixels?
I got my focal length in millimeter.

**Comment by mrharicot** [comment]
If you train on stereo pairs, you should have rectified them, which should give you an intrinsic matrix with a focal length.
Otherwise you need to convert the focal length to pixels:
http://answers.opencv.org/question/17076/conversion-focal-distance-from-mm-to-pixels/

**Comment by keishatsai** [comment]
Thank you for spending time to explain it to me. I am kind of  beginner, but I am getting understand why I barely can turn the disparities into depth image.
I just found out that my focal length was indeed in pixel.
baseline: 65mm
focal length: 275
I tried to reduce the maximum depth by doing the formula you gave; however, the outcome of depth seems to be inverse. I have to use 1 to minus the depth to get the correct order depth, so the formula turns to be ` depth = 1 - ( focal * baseline / ((disparity + 1)/max_depth))`
In my case, would be `depth = 1 - ( 275 * 65 /( (disparity +1) / (max_depth))`
I don't think this is the right way to do it. Do you have any idea why?

**Comment by mrharicot** [comment]
Hi,
The formula should be:
depth = focal * baseline / (disparity + (1/max_depth))
Please keep in mind that this isn't technically correct, but it should help limit the maximum depth.

**Comment by keishatsai** [comment]
I have changed the formula, but I still get the depth in reverse order.

>>> import numpy as np
>>> import scipy.io
>>> import matplotlib.pyplot as plt
>>> mat = np.load('frame-003325_disp.npy')
>>> mat.squeeze().astype(np.float32) / 256
array([[2.96438648e-05, 3.70917260e-05, 3.11938347e-05, ...,
        1.33085105e-05, 1.84990622e-05, 1.42607159e-05],
       [6.57995188e-05, 3.64692642e-05, 5.72057106e-05, ...,
        2.41224243e-05, 1.68622246e-05, 3.18871244e-05],
       [3.74441988e-05, 3.69120971e-05, 5.07449840e-05, ...,
        2.09490881e-05, 1.72933323e-05, 1.70991843e-05],
       ...,
       [7.50381878e-05, 9.99449330e-05, 1.14856470e-04, ...,
        1.51305256e-04, 1.28198837e-04, 9.91879861e-05],
       [7.93225045e-05, 9.81122575e-05, 1.08557702e-04, ...,
        1.48227657e-04, 1.23121281e-04, 9.13897093e-05],
       [9.34020427e-05, 9.53641211e-05, 1.03133534e-04, ...,
        1.33415568e-04, 1.19740107e-04, 1.16340663e-04]], dtype=float32)
>>> depth = 275 * 65 / (mat + (1/mat.max()))
>>> print(depth)
[[793.27527 793.2082  793.26135 ... 793.42255 793.37573 793.414  ]
 [792.94965 793.2138  793.027   ... 793.3251  793.39056 793.25507]
 [793.205   793.20984 793.0852  ... 793.35364 793.38666 793.38837]
 ...
 [792.86646 792.6423  792.50806 ... 792.18036 792.38806 792.64905]
 [792.8279  792.65875 792.56476 ... 792.208   792.4338  792.71924]
 [792.7011  792.6834  792.6136  ... 792.3412  792.4642  792.49475]]
>>> disp_to_img = scipy.misc.imresize(depth,[512,640])
>>> plt.imsave('re_3325.png',disp_to_img, cmap='plasma')
Here is my result:
![re_3325](https://user-images.githubusercontent.com/8175070/36184828-05249426-1171-11e8-8077-165a0679111f.png)

**Comment by mrharicot** [comment]
Hi,
You need to choose a maximum depth yourself, let's say 100m, in this case you would use:
depth = focal * baseline / (disparity + 1e-2)

**Comment by keishatsai** [comment]
Thank you. I will try it later and let you know the results.

**Comment by mrharicot** [comment]
Hi, if your baseline is 65mm the formula should be:
`depth = 275 * 0.065 / (mat + 1e-2)`
However this will not really change the way your depthmap looks like, only its scale.

**Comment by keishatsai** [comment]
Hi, I am a little bit confused that the meaning of scale.
Could you explain it for more detail? Thank you.

**Comment by mrharicot** [comment]
Hi,
As long as you invert disparity, you will get a scaled depth.
The depthmaps will be metric, up to scale, which means that the values will not be meters but can be converted to meters using a single global scale.

**Comment by keishatsai** [comment]
Hello, what do you mean by "invert disparity", is it means that "depth = 275 * 0.065 / (mat + 1e-2)" and the result of this formula will be metric depth. But if I need to convert it to meters, I have to use a single global scale. I hope that I understand correctly.

However, I don't know what do you mean by "a single global scale" and the reason of reversing colours of output of metric depth. Just don't understand that how I can get the depth meters and solve the reversing colours order. 

Do you have idea?
Thank you, 

Keisha

**Comment by mrharicot** [comment]
Hi,

What do you mean by the "reversing the colour order" ?
In the last image you sent, the ordering is correct: brighter means further.

The single global scale means that, if the network trained properly, it will always be consistent in its output: there is only one scalar for all the images to convert the inverse disparity to depth in meters.

**Comment by keishatsai** [comment]
Hi, 
According to your results of paper and the monodepth_simple.py, I thought the brighter means closer.

I try to conclude the point.....I used focal length and baseline to generate depth in meters(ex: disp_to_img), therefore I got a metric with maximum 255 and the minimum 0.
>>> import numpy as np
i>>> import scipy.io
i>>> import matplotlib.pyplot as plt
>>> mat = np.load(
... 'frame-003325_disp.npy')
>>> mat.squeeze().astype(np.float32) / 256
array([[2.96438648e-05, 3.70917260e-05, 3.11938347e-05, ...,
        1.33085105e-05, 1.84990622e-05, 1.42607159e-05],
       [6.57995188e-05, 3.64692642e-05, 5.72057106e-05, ...,
        2.41224243e-05, 1.68622246e-05, 3.18871244e-05],
       [3.74441988e-05, 3.69120971e-05, 5.07449840e-05, ...,
        2.09490881e-05, 1.72933323e-05, 1.70991843e-05],
       ...,
       [7.50381878e-05, 9.99449330e-05, 1.14856470e-04, ...,
        1.51305256e-04, 1.28198837e-04, 9.91879861e-05],
       [7.93225045e-05, 9.81122575e-05, 1.08557702e-04, ...,
        1.48227657e-04, 1.23121281e-04, 9.13897093e-05],
       [9.34020427e-05, 9.53641211e-05, 1.03133534e-04, ...,
        1.33415568e-04, 1.19740107e-04, 1.16340663e-04]], dtype=float32)
>>> depth = 275 * 0.065 / (mat + 1e-2)
>>> disp_to_img = scipy.misc.imresize(depth,[512,640])
>>> print(disp_to_img)
[[125 112 114 ... 172 166 179]
 [109 108 108 ... 168 163 164]
 [ 77  99  96 ... 159 156 134]
 ...
 [ 45  37  31 ...  15  24  34]
 [ 39  36  32 ...  16  22  26]
 [ 36  35  33 ...  17  21  22]]
>>> plt.imsave('20180301.png', disp_to_img,  cmap = 'plasma')

**Comment by keishatsai** [comment]
This is what I have concluded:
load disparities file: `mat = np.load('frame-003325_disp.npy')`
I get the maximum disparity value : `mat.max() = 0.0443939
minimum disparity value : `mat.min()` = 0.00033407987
To make this disparity be in an integer range, I multiply 1000: `m = mat * 1000 `
Now, the maximum disparity value: `m.max()` = 44.39399
Looks like the common disparities value, so I start calculating the depth value:
` depth = 275 * 0.065 / m `
the maximum depth value is `depth.max()` = 53.50517 (meters)
the minimum depth value is `depth.min()` = 0.4026446 (meters)
In the end, my current model can predict around 53 meters in the maximum.
Hope I get this right.

Thank you for the help.

**Comment by moinul95** [comment]
Hello, I am trying to generate depth image using monodepth_simple.py  But when I am saving using the line ,
plt.imsave('20180301.png', disp_to_img, cmap = 'plasma')
I got 4 dimensional array. Why is this? What does the 4th dimension mean here.

Thank you

**Comment by WHUCSLWJ** [comment]
> I have changed the formula, but I still get the depth in reverse order.
> 
> > > > import numpy as np
> > > > import scipy.io
> > > > import matplotlib.pyplot as plt
> > > > mat = np.load('frame-003325_disp.npy')
> > > > mat.squeeze().astype(np.float32) / 256
> > > > array([[2.96438648e-05, 3.70917260e-05, 3.11938347e-05, ...,
> > > > 1.33085105e-05, 1.84990622e-05, 1.42607159e-05],
> > > > [6.57995188e-05, 3.64692642e-05, 5.72057106e-05, ...,
> > > > 2.41224243e-05, 1.68622246e-05, 3.18871244e-05],
> > > > [3.74441988e-05, 3.69120971e-05, 5.07449840e-05, ...,
> > > > 2.09490881e-05, 1.72933323e-05, 1.70991843e-05],
> > > > ...,
> > > > [7.50381878e-05, 9.99449330e-05, 1.14856470e-04, ...,
> > > > 1.51305256e-04, 1.28198837e-04, 9.91879861e-05],
> > > > [7.93225045e-05, 9.81122575e-05, 1.08557702e-04, ...,
> > > > 1.48227657e-04, 1.23121281e-04, 9.13897093e-05],
> > > > [9.34020427e-05, 9.53641211e-05, 1.03133534e-04, ...,
> > > > 1.33415568e-04, 1.19740107e-04, 1.16340663e-04]], dtype=float32)
> > > > depth = 275 * 65 / (mat + (1/mat.max()))
> > > > print(depth)
> > > > [[793.27527 793.2082  793.26135 ... 793.42255 793.37573 793.414  ]
> > > > [792.94965 793.2138  793.027   ... 793.3251  793.39056 793.25507]
> > > > [793.205   793.20984 793.0852  ... 793.35364 793.38666 793.38837]
> > > > ...
> > > > [792.86646 792.6423  792.50806 ... 792.18036 792.38806 792.64905]
> > > > [792.8279  792.65875 792.56476 ... 792.208   792.4338  792.71924]
> > > > [792.7011  792.6834  792.6136  ... 792.3412  792.4642  792.49475]]
> > > > disp_to_img = scipy.misc.imresize(depth,[512,640])
> > > > plt.imsave('re_3325.png',disp_to_img, cmap='plasma')
> > > > Here is my result:
> > > > ![re_3325](https://user-images.githubusercontent.com/8175070/36184828-05249426-1171-11e8-8077-165a0679111f.png)

HI，I also get a reverse depth image that the closer objects are blue instead of yellow. How did you fix this problem?
