### ISSUE TITLE
The results are not as yours

### ISSUE THREAD

**Issue by yeyang1021** [mrharicot/monodepth#11]
I have download the model_cityscapes model and testing. But, the results are not as yours in http://visual.cs.ucl.ac.uk/pubs/monoDepth/results/.
I want to konw why. And how can I get the results like yours.
thank you!

**Comment by mrharicot** [comment]
Hi,
Could you please me bit more specific?
What results and how are they different?

**Comment by yeyang1021** [comment]
The result in matrix just range from 0.14x to 0.15x.  You can find that it is wrong.
In your results: http://visual.cs.ucl.ac.uk/pubs/monoDepth/results/. 
The range is from near 0 to about 0.1.
Why?
There are some things diferent?
I just test the cityscapes models.

**Comment by mrharicot** [comment]
What data do you use for testing?

**Comment by yeyang1021** [comment]
The cityscapes 
All testing data in berlin:
berlin/berlin_000000_000019_leftImg8bit.png berlin/berlin_000000_000019_rightImg8bit.png
.....

**Comment by mrharicot** [comment]
The output disparities we provide are only on the KITTI dataset (kitti or eigen split) you are testing on cityscapes which is a different dataset. 
We did not upload the output disparities for the cityscapes dataset.

**Comment by yeyang1021** [comment]
Thank you for your answer.
The name of results in the website misleading me.
So, I need train a cityscapes model.

**Comment by giyagaga** [comment]
@mrharicot 
Hello, I also download the model_cityscapes model and tested on the cityscapes test dataset and got  the disparities_pp.npy, then i used the evaluation code to evaluation the results, but i got the results are not as yours in the paper:
`  abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
    0.4235,  3159.2678,  18126.822,      1.910,     67.391,      0.338,      0.716,      0.762
`
I did change the focal to 2262 and the baseline to 0.22.
`
width_to_focal[2048] = 2262

def convert_disps_to_depths_cityscapes(gt_disparities, pred_disparities):
    gt_depths = []
    pred_depths = []
    pred_disparities_resized = []
    
    for i in range(len(gt_disparities)):
        gt_disp = gt_disparities[i]
        height, width = gt_disp.shape

        pred_disp = pred_disparities[i]
        pred_disp = width * cv2.resize(pred_disp, (width, height), interpolation=cv2.INTER_LINEAR)

        pred_disparities_resized.append(pred_disp) 

        mask = gt_disp > 0

        gt_depth = width_to_focal[width] * 0.22 / (gt_disp + (1.0 - mask))
        pred_depth = width_to_focal[width] * 0.22 / pred_disp

        gt_depths.append(gt_depth)
        pred_depths.append(pred_depth)
    return gt_depths, pred_depths, pred_disparities_resized`

I do not know what went wrong,??

**Comment by mrharicot** [comment]
Hi,
We did not test our model on the cityscapes dataset as they do not have reliable depth data.
What results are you comparing it with?
