### ISSUE TITLE
Results not matching for eigen split

### ISSUE THREAD

**Issue by madhubabuv** [mrharicot/monodepth#110]
Hello,

I have downloaded the disparities_eigen from your results. After running the evaluate_kitti.py with Eigen crop with cap 80m, the numbers are not matching with the original paper. But the garg_crop results are exactly matching. Please help me, I have to compare the results.

Your paper states
abs     sq_rel   rms     log_rms      a1         a2        a3
0.148   1.344   5.927   0.247      0.803     0.922     0.964
I got this
0.1691   1.7212   6.538   0.269      0.770      0.906     0.955

Thanks in advance.

**Comment by mrharicot** [comment]
Hi,
You have to use --garg_crop to compare with the paper. 
For the KITTI split we do not crop, for Eigen split we use --garg_crop.
We also show the uncropped results in Table 2.

**Comment by madhubabuv** [comment]
Thank you, got the same result. I am closing the issue.
