### ISSUE TITLE
Not getting proper depth maps for frames capture from video using Opencv.

### ISSUE THREAD

**Issue by vineetkr137** [mrharicot/monodepth#112]
Hi,
 results are same when running monodepth_simple.py on single image, while running on video using Opencv to capture frames is producing not so proper depth maps. the results are something like edge detection.

**Comment by mrharicot** [comment]
Hi,
Did you convert the frames to RGB then to float32 in the range [0, 1]?

**Comment by vineetkr137** [comment]
Yes,
I am converting the frames to RGB then to float32 in the range [0, 1]. but still it is showing the same results.

**Comment by mrharicot** [comment]
Did you resize the images to 256x512?
