### ISSUE TITLE
Train depth directly

### ISSUE THREAD

**Issue by melights** [mrharicot/monodepth#113]
Hi mrharicot,

Thank you for sharing this great work. Training disparities and synthesize the other view is a brilliant idea. However, training disparities will have some problems such as training on datasets with different baselines, and how to estimate depth without baseline using monocular camera. Do you think it is possible to train depth directly and using the baselines to convert to disparities and synthesize the other view and compute loss?

**Comment by mrharicot** [comment]
Hi,
Yes, it is entirely possible! It is done by several related papers such as:
https://people.eecs.berkeley.edu/~tinghuiz/projects/SfMLearner/

I hope this helps!

**Comment by melights** [comment]
thanks!
