### ISSUE TITLE
Make3d camera parameters

### ISSUE THREAD

**Issue by jpyusiong** [mrharicot/monodepth#114]
Hi, In Figure 7, you presented the qualitative results on Make3D. I would like to ask about the focal length and baseline values that you used for the depth maps? I tried searching the code for these parameters but it seems I could not find it.

Thank you.

**Comment by mrharicot** [comment]
Hi,
We cropped the images to the same ratio as cityscapes and used its focal length and baseline parameters.
For cityscapes the baseline is 0.22m and the focal is 2262 for a width of 2048.

**Comment by jpyusiong** [comment]
I see. Why is it that you chose the CS model and not the K model or CS+K model for the Make3D evaluation?

**Comment by mrharicot** [comment]
The CS data is of much higher quality (variety and dynamic range) and has a less restrictive aspect ratio.
It also looks closer to the Make3D pictures.

**Comment by jpyusiong** [comment]
Thank you.
