### ISSUE TITLE
Stereo version VS monocular 

### ISSUE THREAD

**Issue by OzzyW** [mrharicot/monodepth#115]
Hello Dr. Clément Godard, Dr. Oisin Mac Aodha and Dr. Gabriel J. Brostow,

I really like your approach in the paper and have a couple of questions:

1) Regarding the stereo version model. Can you elaborate what you meant by "where the network’s input is the concatenation of both left and right views" (section 4.3)?  What exactly changed in the input with the stereo version?

2) Did you find **any advantage** in the monocular model over the stereo model (except the stability issue after 12 epochs)?

**Comment by mrharicot** [comment]
Hi,

The stereo model takes **two** images as input instead of **one**. 
Which means that the stereo model needs **two** images at test time as well. This is a significant disadvantage over the monocular model.

**Comment by OzzyW** [comment]
Oh I see, thank you for your prompt reply! 

Also is the testing time you report in the paper (less than 35 ms) the same as the runtimes reported in the KITTI stereo benchmark (http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo)? If so that makes your model faster then most of the stereo models there (yet less accurate) or am I missing something?

Have a great weekend!

**Comment by mrharicot** [comment]
Yes the stereo model is indeed relatively fast but falls short in terms of accuracy.
We did not try to get the stereo model to achieve good scores, but just wanted to show that the self-supervision also works for stereo at test time.
