### ISSUE TITLE
The shape of disp_left_est[0]

### ISSUE THREAD

**Issue by Eddylib** [mrharicot/monodepth#119]
Hi,
   Thanks for your brilliant work. :)
    I get confused in the shape of disp_left_est[0].  It comes from disp_est,  and then disp_left_est[0] has a shape of  (2, 128, 256, 1) as I tested.
    I found the final output is disp_left_est[0][0], (in code: disparities[step] = disp[0].squeeze(), where disp is the output of disp_left_est[0]), but what is the meaning of disp_left_est[0][1].
here i list the first and second pair of disp_left_est computed from first and second kitti test data.
first 
![00](https://user-images.githubusercontent.com/20674830/36945813-5cceb5a4-1fee-11e8-8f8e-707e6a8fb901.jpg)
![10](https://user-images.githubusercontent.com/20674830/36945817-64e5dc4a-1fee-11e8-9d3a-f1002f6c4137.jpg)
second
![01](https://user-images.githubusercontent.com/20674830/36945819-6b1b6f80-1fee-11e8-96bc-95b7280ff344.jpg)
![11](https://user-images.githubusercontent.com/20674830/36945821-6f28e1c0-1fee-11e8-88ea-54213affb9fb.jpg)

   I haven't find description of this. Did I loss something in the paper?...
Thanks~

Regards

**Comment by mrharicot** [comment]
Hi,

I must say I am a little confused about this too.
Are you talking about the test code?
Having a size of (2, 128, 256, 1) means that there is a batch size of two.
When we evaluate the model, we push two images at a time: the current frame and the flipped image.
We then flip back the disparity of the second image and merge.

It looks like the second input image produces garbage in this case, did you modify the code?

**Comment by Eddylib** [comment]
Yes, I run the  test code, and then look deeper into it. 
Then I modified code for output to see the shape of many outputs.
Now I find another place that corresponding to the technique of "post processing" in the paper which use the second image in the "(2, 128, 256, 1)" batch.

`

    def post_process_disparity(disp): #disp_left_est[0].squeez()
        _, h, w = disp.shape #4*h*w
        l_disp = disp[0,:,:]
        r_disp = np.fliplr(disp[1,:,:])
        m_disp = 0.5 * (l_disp + r_disp)
        l, _ = np.meshgrid(np.linspace(0, 1, w), np.linspace(0, 1, h))
        l_mask = 1.0 - np.clip(20 * (l - 0.05), 0, 1)
        r_mask = np.fliplr(l_mask)
        return r_mask * l_disp + l_mask * r_disp + (1.0 - l_mask - r_mask) * m_disp
`
But this process will take some time to understand....for me.
Thank you for your reply.

**Comment by mrharicot** [comment]
Have a look at Section 2 in the supplementary material:
https://arxiv.org/pdf/1609.03677.pdf

**Comment by Eddylib** [comment]
Ok~Thanks for the insights.
