### ISSUE TITLE
How to access to unscaled disparity map

### ISSUE THREAD

**Issue by aloukkal** [mrharicot/monodepth#120]
Hi Clément, 

I am trying to access the unscaled (I want it in the same format than the one outputted by the open cv feature)  disparity map outputted by your network to use it as an offset for an image indexes, could you please tell me what is the multiplicative factor I have to use on disp_left_est ?

**Comment by mrharicot** [comment]
Hi,
The disparity map is normalized, which means that you need to scale it by the image width to get pixel disparities.

**Comment by aloukkal** [comment]
Ok thanks, that was my guess after reading you bilinear sampler code, but I am still getting weird values. I am making a modified version of your code, I must have done something wrong.
