### ISSUE TITLE
use pre-trained models error

### ISSUE THREAD

**Issue by shwei83** [mrharicot/monodepth#121]
Hi, mrharicot  I try to run the monodepth_simply.py ,so l input
%run monodepth_simple.py --image_path C:\Users\user\Desktop\monodepth-master\my_image.jpg --checkpoint_path C:\Users\user\Desktop\monodepth-master\models\model_cityscapes
,but it has error
INFO:tensorflow:Restoring parameters from C:\Users\user\Desktop\monodepth-master\models\model_cityscapes
UnicodeEncodeError: 'utf-8' codec can't encode character '\udca6' in position 2466: surrogates not allowed
do you know what's wrong?

**Comment by mrharicot** [comment]
Hi,
I have never seen this error before, it seems that it is confused by a unicode character.
Could you try with python2?
