### ISSUE TITLE
Is there something wrong in the function post_process_disparity?

### ISSUE THREAD

**Issue by Eric-BB** [mrharicot/monodepth#123]
Hi, mrharicot! Is there something wrong in the function post_process_disparity?

l_mask = 1.0 - np.clip(20 * (l-0.05), 0, 1)

Thank you!

**Comment by mrharicot** [comment]
Hi,
As far as I know the post process disparity function works fine.
What do you think is wrong?

**Comment by Eric-BB** [comment]
Thanks for your answer! I just think there is a  type error in 20 * (l-0.05)? Maybe I'm wrong!

**Comment by Eric-BB** [comment]
Thanks for your answer! I just think there is a  type error in 20 * (l-0.05)? Maybe I'm wrong!

**Comment by mrharicot** [comment]
What do you mean by a type error?
