### ISSUE TITLE
equation 4 in the paper

### ISSUE THREAD

**Issue by melights** [mrharicot/monodepth#126]
Dear @mrharicot ,

In the equation 4 of your paper, should the right disparity coordinate **minus** the left disparity value to get the corresponding position of the left disparity?  
![codecogseqn 1](https://user-images.githubusercontent.com/10015917/37377078-d13513ce-271f-11e8-90e6-0b80c8d72ea1.gif)
Correct me if I was wrong.

Best regards,
Long

**Comment by mrharicot** [comment]
Hi,
I think the original notation is confusing, in order to match the sampling notation used everywhere else in the paper we should have used:

![image](https://user-images.githubusercontent.com/5363877/38755339-4fc4a0ce-3f5d-11e8-9774-9d10661550da.png)

Does it make more sense like this?

**Comment by mrharicot** [comment]
Hi,

It should be a minus, like in your first equation.
https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L85

**Comment by melights** [comment]
Thanks!
