### ISSUE TITLE
The output picture

### ISSUE THREAD

**Issue by ChuangbinC** [mrharicot/monodepth#127]
Hi,
Thanks for your brilliant work. :)
I want to make sure the output picture of the network is a disparity map or depth map?
![000000_10_disp](https://user-images.githubusercontent.com/18183832/37565916-d6e8aa6c-2aec-11e8-999c-e2746e84718d.png)

Thank~~~~

**Comment by mrharicot** [comment]
Hi,
Disparity is scaled inverse depth, which means that in disparity images brighter objects are closer, like the image you posted.

**Comment by ChuangbinC** [comment]
@mrharicot  Thanks. I have a question.You use 4 scaled disparity in network but why it output 1 scale disparity in "test" mode. Where  is the code which combines them into 1 scale disparity?

**Comment by mrharicot** [comment]
Hi,
They are not combined, we just use the highest resolution one.

**Comment by ChuangbinC** [comment]
@mrharicot Thanks for your answer !!  : )
