### ISSUE TITLE
Do you have a chance to have a Cityscapes stereo model?

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#128]
Hi,

Like the title. There is only Kitti dataset has stereo training model. 
Could you provide the Cityscapes dataset one?
Thank you !

**Comment by mrharicot** [comment]
Hi,
We do not have a pre-trained stereo model on Cityscapes.

**Comment by keishatsai** [comment]
Or could you provide the detail parameters while training pre-trained Cityscapes model on VGG and ResNet?
Thank you ~

**Comment by mrharicot** [comment]
Hi,
As we state in the paper, we kept all parameters identical, they are currently the default ones.

**Comment by keishatsai** [comment]
Hi,
I see. Thanks for the reply :)
