### ISSUE TITLE
The shape of input left images

### ISSUE THREAD

**Issue by ChuangbinC** [mrharicot/monodepth#129]
Hi, I find that the shape of input images is [2,256,512,3] in the "monodepth_simple.py" file and I want to know if the shape of the left images which are put into the model is also [2,256,512,3] in training or just [256,512,3]?
Thanks!!!!!

**Comment by mrharicot** [comment]
Hi,
For monodepth_simple we feed the input image twice, the second time flipped.
This is used for post-processing and is not necessary.
The first dimension of the tensor is the batch size, here 2.
If you only want one image you still need a 4D tensor: [1,256,512,3]
I hope this helps!

**Comment by ChuangbinC** [comment]
Thank you!!! : )
