### ISSUE TITLE
Shape mismatch error with "--do_stereo"

### ISSUE THREAD

**Issue by jeongc** [mrharicot/monodepth#13]
Hi

I tried to inference test with pretrained your model with "--do_stereo", but I saw the following error. But without "--do_stereo", every tests completed without any error. Please let me know how to resolve.

Regards,
-CJ

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [7,7,6,32] rhs shape= [7,7,3,32]
         [[Node: save/Assign_37 = Assign[T=DT_FLOAT, _class=["loc:@model/encoder/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/encoder/Conv/weights, save/RestoreV2_37/_129)]]

**Comment by mrharicot** [comment]
Hi CJ,

All the pretrained models are monocular, which is why the network expects
only 3 channels as input instead of 6.

**Comment by jeongc** [comment]
Hi

Thanks for your reply. Can you share one of your weights for stereo configuration? 

Regards,
CJ

**Comment by jeongc** [comment]
Hi 

I tried to train, but I saw OOM errors as below. What's minimum GPU/CPU memory requirement to train on KITTI dataset for example? I know my GPU is not powerful one, and would buy new one. So I want to know requirement. Thanks in advance.

Regards,
CJ


W tensorflow/core/common_runtime/bfc_allocator.cc:274] ************************************************************************************************_***
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 34.04MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[8,130,66,130]
         [[Node: model/decoder/Conv_10/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/decoder/Pad_10, model/decoder/Conv_10/weights/read)]]

**Comment by mrharicot** [comment]
What size did you use as input?

**Comment by jeongc** [comment]
Closed since I could train now.

**Comment by mrharicot** [comment]
Glad to hear that!
Could you explain what was the problem?

**Comment by robotiste** [comment]
I am facing the problem now!
@jeongc it would be great if you could tell how you resolve this?

@mrharicot I think this is not a issue of input size.
