### ISSUE TITLE
Distortion by re-projecting disparity map to 3d point cloud

### ISSUE THREAD

**Issue by ReutherMa** [mrharicot/monodepth#130]
Hi,

I tried to re-project the from the monodepth-network produced disparity maps into a 3d scene and run into an issue.
To verify my results I used on the one hand the same metrics mentioned in your paper and got comparable results on your pre-trained kitti model. On the other hand I generated point clouds from the disparity maps to verify the quality of the predicted depth visually.
By doing so I detected that the view point (from which I take a look at the point cloud) does keenly influence my estimation of the quality produced by the predicted depth. 
From the 'normal' view point the prediction looks quite good, as you can see in this screenshot:
![bildschirmfoto vom 2018-03-22 11-54-33](https://user-images.githubusercontent.com/22811302/37767154-5f79c3dc-2dc9-11e8-9407-f0b4eefbf1ee.png)
 
But moving the view point to a higher position in the scene shows that the prediction is badly distorted:
![bildschirmfoto vom 2018-03-22 11-54-47](https://user-images.githubusercontent.com/22811302/37767209-99cb8de0-2dc9-11e8-9843-189486ae06a1.png)
and
![bildschirmfoto vom 2018-03-22 11-55-06](https://user-images.githubusercontent.com/22811302/37767218-a5bb7cbe-2dc9-11e8-8e09-c57c2a8909e2.png)

My question: Is it normal that the predicted 3d points are distorted in this way (because of the accuracy of the prediction, ...) or have I made a mistake during re-projection to 3d?

br

**Comment by mrharicot** [comment]
Hi,
When viewed in 3d these depthmaps aren't particularly great, it is expected.
I am not quite sure whether your pointclouds are correct though.
Using the pixel colors helps a lot for viewing.
How do you backproject?
The current code has zero minimum disparity, which means that the maximum depth is unbounded.
You can "solve" this by adding a small epsilon to the inverse depth before inverting it.
I hope this helps!
