### ISSUE TITLE
I am confuse about the size of output disp

### ISSUE THREAD

**Issue by LeisureLiu** [mrharicot/monodepth#131]
Hi,
I have an question about the size of output disp, as you resize the input image size to [512,256],  I thought the size of disp should also be [512,256], but why it is the same to the original input image size.
forgive my stupid question.

**Comment by mrharicot** [comment]
Hi,
Are you talking about monodepth_simple?
In this case I resize the disparity to the original image size just for visualization.

**Comment by LeisureLiu** [comment]
oh, yeah~ thank you for answer.
