### ISSUE TITLE
C++ Code ?

### ISSUE THREAD

**Issue by ZeroCool11000** [mrharicot/monodepth#132]
Are there any C/C++ code implementations ? It would be nice have!!!

Best regards.

**Comment by mrharicot** [comment]
Hi,
Not that I know of unfortunately.
The model is simple enough that you could probably reproduce it in any C++ deep learning framework then load the weights.

**Comment by a-jahani** [comment]
Below is the CPP tensorflow of this repo, which we've been using it for our [CNN-SVO](https://github.com/yan99033/CNN-SVO) algorithm:
[mondepth CPP](https://github.com/yan99033/monodepth-cpp)
The inference speed is almost 2x more than python version.

You can also follow other instructions online of how to use tensorflow in cpp.
