### ISSUE TITLE
Eigen split

### ISSUE THREAD

**Issue by ehabhelmy82** [mrharicot/monodepth#135]
Hello
Could kindly give me a link to download the 697 reprojected lidar point clouds from the raw KITTI data (following Eigen et al.) to get the results in table 2
Thanks

**Comment by mrharicot** [comment]
Hi,

I unfortunately do not own the data so you have to generate it yourself:
You can download all the KITTI files following the instructions here:
https://github.com/mrharicot/monodepth#kitti

You can then modify the evaluation code to save the reprojected lidar point clouds (gt_depths here):
https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py#L38

**Comment by ehabhelmy82** [comment]
Thanks for your fast reply, but I did not understand how to mdify? can you help me by telling the required modification?
When I faced this problem with Kitti split I downloaded data scen flow from the following link : http://www.cvlibs.net/download.php?file=data_scene_flow.zip
Do not you have similar one to download the required data for Eigen split?

**Comment by mrharicot** [comment]
Hi,
Please read carefully the instructions here:
https://github.com/mrharicot/monodepth#kitti
You need to download the raw dataset which is quite large.

Then you can save the reprojected point clouds `gt_depths` created here:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py#L38
`gt_depths` is a list of numpy arrays, you can simply save them or create a numpy array of arrays and save it.
