### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by ehabhelmy82** [mrharicot/monodepth#136]
Hi
In my previous traditional recognition tasks I used to to split the data set to either (training an testing sub sets) or (training , validation and testing subsets). I am confused about the splits you used (training, testing and evaluation) what is the different between testing and evaluation? Does the results mentioned in the paper belongs to evaluation only?

**Comment by mrharicot** [comment]
Hi,
What is confusing you exactly?
All the results mentioned in the paper only correspond to the 697 test frames for the Eigen split or the 200 test frames for the KITTI split.

**Comment by ehabhelmy82** [comment]
What is the difference between the following phases:
Training, testing and evaluation?

**Comment by ehabhelmy82** [comment]
one more thing:
Concerning the steps mentioned in the code page "https://github.com/mrharicot/monodepth" I followed the following steps :
1. python monodepth_main.py --mode train --model_name my_model --data_path ~/data/KITTI/ \
--filenames_file ~/code/monodepth/utils/filenames/kitti_train_files.txt --log_directory ~/tmp/

2. python monodepth_main.py --mode test --data_path ~/data/KITTI/ \
--filenames_file ~/code/monodepth/utils/filenames/kitti_stereo_2015_test_files.txt --log_directory ~/tmp/ \
--checkpoint_path ~/tmp/my_model/model-181250

3. python utils/evaluate_kitti.py --split kitti --predicted_disp_path ~/tmp/my_model/disparities.npy \
--gt_path ~/data/KITTI/

As I understood and according to the mentioned steps you trained on KITTI data set and tested using stereo version (concatenated left and right image) and then evaluated using the KITTI split is that rigth?
The question is what result should I got? that for stereo in table 1 or that for KITTI split in table 1?

I got the following result which is very closed (but not exact)  to that for KITTI split not Stereo one, here is my results:
abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
    0.1217,     1.3208,      6.142,      0.216,     31.581,      0.841,      0.938,      0.974
What is your comment?

**Comment by mrharicot** [comment]
Hi,
In our case evaluation means testing.
The stereo model we mention in the paper is a different experiment, you just trained a monocular model.
The results will always be slightly different because of the stochastic nature of deep learning.

**Comment by ehabhelmy82** [comment]
in case that evaluation means testing why they are carried out as different steps one after one and why I just got output results from evaluation step?
As long as I trained a monocular model why (according to the steps mentioned in github link) should I test with "kitti_stereo_2015_test_files.txt" not "kitti_test_files.txt"?
How can I excute the stereo model mentioned in the paper?
In the paper, what do you mean with "Ours cap 50m"
How to train using Kitti and cityscape? should I put both data sets together in one path and the create new txt file that contain data in both cityscapes_train_files.txt and kitti_train_files.txt 
one last question:
how do you do finetuning? which command?

**Comment by mrharicot** [comment]
I am afraid I don't have the time to answer all your questions.
Please read the readme as well as the paper carefully, all your questions are answered there.
