### ISSUE TITLE
Testing on CPU/GPU

### ISSUE THREAD

**Issue by KengChiLiu** [mrharicot/monodepth#137]
Hi,
I'm testing cityscapes with the command like

python monodepth_main.py --mode test --data_path ~/data/KITTI/ --filenames_file ~/code/monodepth/utils/filenames/kitti_stereo_2015_test_files.txt --log_directory ~/tmp/ --checkpoint_path ~/tmp/my_model/model-181250

you provided. 

However, it seems to be running on CPU not GPU. How can I change it ?
Thank you

**Comment by mrharicot** [comment]
Hi,
If you have a CUDA compatible gpu and installed the correct tensorflow, it should run on the GPU automatically.
Check https://www.tensorflow.org/install/
