### ISSUE TITLE
How to get the figures as given in the paper

### ISSUE THREAD

**Issue by Shankhanil006** [mrharicot/monodepth#138]
Hi ,
First of all thank you for giving a detailed analysis of your method in your CVPR paper. In that context I wanted to know from where did you get the depth images of others method like Eigen et al, Liu et al etc. for comparison in figure 4 and figure 7.

**Comment by mrharicot** [comment]
Hi,
You can find Eigen's results on his webpage, as for Liu and others I am not sure I remember.
I usually email the authors and they respond quite quickly.

**Comment by Shankhanil006** [comment]
Hi,
Thank You for your response. Could you please share the image details which were used for comparison.

**Comment by Shankhanil006** [comment]
Thank You very much .
