### ISSUE TITLE
About which focal and baseline should use to convert to depth while inference on different datasets?

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#139]
I am struggling with this issue because I find some people had encountered the same problem.
I have tried using the focal and baseline of training one while doing inference on different dataset. 
The depth which calculated with training sets’ focal and baseline was pretty large, over 1000 meters (if the real meter is 2m), however, I got reasonable results by using testing set’s focal and baseline. Is there anything wrong with my implementation?

my testing sets(width: 640) focal and baseline is 275 in pixel  and 0.065m
the training sets (width: 1242)focal and baseline is 721 in pixel and 0.54m
`depth = focal * baseline / (640 * disp)`

If I didn't do anything wrong, I doubt that all the images have been done with the pre-process by resizing to the same size [256 * 512] , so there is should be no difference between training and testing. 
To be concluded,  the depth calculation is depend on the testing dataset's focal and baseline.
Please correct me, if I am wrong. 
Thank you :)

**Comment by mrharicot** [comment]
Hi,

To be clear: _in its current form_, monodepth needs to have test images with a focal length identical to the dataset it was trained with. **You cannot expect good results otherwise.**

When testing on images which different characteristics from the training set, it is not clear to me how to convert the disparities into depths.

A reasonable way could be to measure something of known size in the test images and use this to find a reasonable scaling.
I never studied how the network behaves on images of different focals.

**Comment by keishatsai** [comment]
Hi,
Thanks for replying. :)
You suggest that measure something with known size in test image. By this means,  there is a table in the test images. If I have known the real size of the table in the reality, then I can inference the scale between the training and testing data instead of using width as scale only?

**Comment by mrharicot** [comment]
Hi, exactly!

**Comment by keishatsai** [comment]
Hello,
Just wondering...The size of object can be vary from the different distance, so the question is that how to measure it by looking at the test image, especially, the image was taken from 7 meter? It might look smaller than its real size.

**Comment by mrharicot** [comment]
Hi,
You can use the predicted depth of the object.
Even more simple, if you know how far an object is you can just scale the depthmap to make it match the measurement.

**Comment by keishatsai** [comment]
Hello, 
That is a good suggestion. I am going to try it now.
Thank you:)
