### ISSUE TITLE
Cityscape error

### ISSUE THREAD

**Issue by ehabhelmy82** [mrharicot/monodepth#140]
Hello
When i use Cityscape data set (leftImg8bit_trainvaltest.zip, rightImg8bit_trainvaltest.zip, leftImg8bit_trainextra.zip and rightImg8bit_trainextra.zip ) to train the proposed network I got the following erroe:

Invalid argument: Shape mismatch in tuple component 0. Expected [256,512,3], got [256,512,1]

Notice, it run many patches and then give me this error after that complete two extra patches and then give me the following erroe:

OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 7)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
Can you help me fix that

Thanks

**Comment by mrharicot** [comment]
Hi,
It seems that you are loading a black and white image ([256,512,1] instead of [256,512,3]).
What do you mean by patches?
Did you modify the code in any way?
Are you sure the files follow the folder structure expected by the code?

**Comment by ehabhelmy82** [comment]
Thank you very much for your reply
I found that he data set contain one error image that is all black, I replaced it and the code already works.
According to results mentioned in table 1 as CS (5th row), which data (filename .txt files)  you used during testing and evaluation after training on cityscape only to get these results?
Thanks

**Comment by mrharicot** [comment]
Hi, 
as mentioned in the paper Table 1 is on the KITTI split (kitti_stereo_2015_test_files.txt) while Table 2 is on the Eigen split (eigen_test_files.txt).
Also remember that when testing on the eigen split, you need to use `--garg_crop`.

**Comment by mrharicot** [comment]
Hi,
The evaluation code that your used makes use of the baseline and focal of KITTI.
In the paper we used the baseline and focal of Cityscapes which explains the difference.

**Comment by ehabhelmy82** [comment]
Thanks for you comment but what should I modify to get the reported results?
There is no file with name "evaluate_cityscape.py" in the code, or kindly tell me how to modify the one i have to use baseline and focal lenght of cityscape.
Thank you very much for your time

**Comment by mrharicot** [comment]
Hi,
You need to edit the evaluation code which converts the disparity map to a depth:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py#L44

You need to replace the focal and baseline with the values from cityscapes which you can find here:
https://github.com/mrharicot/monodepth/issues/49#issuecomment-330595397

**Comment by ehabhelmy82** [comment]
Thank you very much for your valuable answers

**Comment by Oceanland-428** [comment]
Hi @ehabhelmy82 
I met the same error.
After "batch 10100", I got "Expected [256,512,3], got [256,512,1]", and two more batches then the program crushes.

I used Cityscapes. Do you still remember at which folder you found the broken image? Also, how do you check if you have a broken image or not? Do you read every image and check if the shape of the image is [1024, 1024, 3]?

Thank you very much!

**Comment by Huang-Jin** [comment]
I also faced such problem when I used the CityScapes dataset.

**Comment by Huang-Jin** [comment]
Oh, I find the problem.
The parameter "--dataset" should be set to "cityscapes".
Otherwise, this error will occur.
