### ISSUE TITLE
Disparity map smoothness

### ISSUE THREAD

**Issue by alwynmathew** [mrharicot/monodepth#141]
How did you smooth your disparity maps shown in your paper so well?

**Comment by mrharicot** [comment]
Hi,
I am not sure I understand your question, why are you asking?
There is no explicit smoothing outside of the smooth loss.
The post-processing does improve the smooth look of the predicted depth maps though.

**Comment by alwynmathew** [comment]
When I tried to replicate your work, I got something like this

![capture](https://user-images.githubusercontent.com/26373373/39086479-aa66c630-45af-11e8-9569-28c86085114b.PNG)

But your disparity map looks much better. How is it? What are the post-processing I should follow to reach your disparity image quality?

**Comment by alwynmathew** [comment]
> This depth map seems severely quantized, did it look like this before you saved it?
 
I directly saved output of the network to jpg file using PIL Image.

>It also seems that you are not using multi-scale, which explains the tears visible in the upper part of the depth map.

I did use multi-scale as in the paper. Please en-lighting me how multi-scale network and tear in disparity are connected.

>What other differences are there between your implementation and mine? Is it a faithful reimplementation?

I have made few changes in the network but still its a Unet. Rest are mostly identical.

**Comment by mrharicot** [comment]
I am afraid I cannot help you as you are not using my code and I do not know what modifications you did.

The tears are caused by the fact that the network will have a harder time matching things that are far away from each other. This is the same reason why many stereo and optical flow methods use coarse-to-fine approaches.

**Comment by alwynmathew** [comment]
Thank you for the info 😃
