### ISSUE TITLE
How to use the disparity map to calculate the image depth

### ISSUE THREAD

**Issue by xielinjiang** [mrharicot/monodepth#143]
I encountered a problem when using parallax maps to generate depth maps. The parallax matrix finally output by the algorithm is 256*512, but if I use this algorithm to predict the depth information in the KITTI dataset, and the image size in the KITTI dataset is 371*1242, this size is inconsistent and how should it be converted?

**Comment by mrharicot** [comment]
Hi,
Simply reshape the disparities to the KITTI image size and multiply them by that image width (here 1242) to get proper disparities in pixels.

**Comment by xielinjiang** [comment]
Thank you very much for your answer, I have found the solution.

**Comment by andrearama** [comment]
@mrharicot  could you explain why you need to multiply by the image width? 
It actually works, but I do not understand the reason behind it.

Thanks!
