### ISSUE TITLE
Do stereo model results

### ISSUE THREAD

**Issue by ehabhelmy82** [mrharicot/monodepth#146]
Hi
I tried to get the stereo model results in table 1
I used the following commands
python3 monodepth_main.py --mode train --model_name Kstereo --data_path /data/ehab/KITTI_Unzipped/ --filenames_file ./utils/filenames/kitti_train_files.txt --log_directory ~/KITTIstereo/ --do_stereo

python3 monodepth_main.py --mode test --data_path /data/ehab/data_scene_flow/ --filenames_file ./utils/filenames/kitti_stereo_2015_test_files.txt --log_directory ~/KITTIstereo/ --checkpoint_path ~/KITTIstereo/Kstereo/model-181250 --do_stereo

python utils/evaluate_kitti.py --split kitti --predicted_disp_path ../KITTIstereo/Kstereo /disparities.npy --gt_path ../data/data_scene_flow

but I got the following alarma followed by a strange results below:

/home/ehab/monodepth-master/utils/evaluation_utils.py:62: RuntimeWarning: divide by zero encountered in divide
  pred_depth = width_to_focal[width] * 0.54 / pred_disp
   abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
    0.9082,    14.2129,     19.197,      2.609,    100.000,      0.000,      0.000,      0.000
Can you help me find out what is going wrong ?
Thanks

**Comment by mrharicot** [comment]
Hi,
Can you share an example output disparity map?
As we state in the paper, the stereo model is unstable and we stopped training it after 12 epochs.
It was also done as a side experiment just to show that the architecture and the loss were also capable of learning stereo and should not be seen as a main result.

**Comment by ehabhelmy82** [comment]
Hi
Thank you very much for your reply
How to access output disparity map?
Thanks
