### ISSUE TITLE
Ours cap 50m

### ISSUE THREAD

**Issue by ehabhelmy82** [mrharicot/monodepth#147]
Hi 
How can I get the results wit cap 50m in table 2? which code should I excute and what is the modifications should I do?
Thanks

**Comment by mrharicot** [comment]
Hi,
Set the `--max_depth` argument to 50:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py#L11

**Comment by ehabhelmy82** [comment]
Thank you very much
one last question:
how to get the last two rows in table 2 (Our pp uncropped and Our resnet pp uncropped)?
Thanks again

**Comment by ehabhelmy82** [comment]
Thank you very much for your time
What about NO LR in table 2, how to get this result?
Thanks

**Comment by mrharicot** [comment]
You need to disable all the losses which are related to the reconstruction of the right image as well as the left-right consistency loss.

**Comment by ehabhelmy82** [comment]
Thanks
