### ISSUE TITLE
Make3D

### ISSUE THREAD

**Issue by jpyusiong** [mrharicot/monodepth#154]
Hi, 

I would like to clarify on the Make3D evaluation step. This is how I understood your paper.  The 134 test images of the Make3D dataset are presented to the CS trained model, and these images are then resized with h=256 and w =512. The predictions produced by the model have a resolution of 256 x 512.

To evaluate the performance of the model on the Make3D dataset, you compared the predicted maps with the ground-truth maps. However, to obtain the predicted depth maps you used the camera parameters of the cityscapes dataset: the baseline is 0.22m, and the focal is 2262 for a width of 2048.

Does this mean you first resized the predicted maps from 256x512 to 1024x2048 to match cityscapes' image resolution, then computed for Z=(focal length x baseline)/resized predicted maps like how it is done on the KITTI predictions?

However, the ground truth resolution of the Make3D test images is 305 x 55 x 1 (4th channel). When evaluating the performance, did you resize the ground-truth to 1024x2048 and then computed for the errors? When is the central cropping performed?

Thank you.

**Comment by mrharicot** [comment]
Hi,
We actually cropped the top and bottom of the make3d images so they had a 2x1 ratio, then resized to 256x512.
We also cropped the top and bottom of the Make3D ground truth depths, making them 305x21 iirc.
We then resized our predicted depthmaps to match the size of the make3d depths and evaluated the methods at that resolution.

**Comment by jpyusiong** [comment]
Thank you for the clarification.
