### ISSUE TITLE
Get actual distance from Plasma image

### ISSUE THREAD

**Issue by sg2308** [mrharicot/monodepth#155]
Hello !
I would like to know how can we get the actual depth of the pixel in meters from the plasma image or from .npy file created??

**Comment by mrharicot** [comment]
Hi,
The colormap is just a visualization.
The .npy corresponds to a normalized disparity, you can obtain the depth following my explanations here:
https://github.com/mrharicot/monodepth/issues/49#issuecomment-330595397
