### ISSUE TITLE
Network Architecture

### ISSUE THREAD

**Issue by YiJingMolly** [mrharicot/monodepth#158]
Hello ~
I am interesting in your paper.
I know the model  architecture be shown in Supplementary Material Page1.
I want to know if I use Resnet50 to training .
Is the encoder architecture like below?
![image](https://user-images.githubusercontent.com/39803851/40792074-98d1f1f6-652b-11e8-828d-cfa399ac06bf.png)

And how many layers of convolution or upsampling or others in the decoder?

Thanks~

**Comment by mrharicot** [comment]
Hi,
You can see the details of the architecture here:
https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L232
The decoder is identical as the VGG model.
We also have a rundown of the model in supp mat:
https://arxiv.org/pdf/1609.03677.pdf

**Comment by YiJingMolly** [comment]
Thank you for your reply.
And I am a beginner.
Is the network architecture be drawn into a graphic?
Can make me understand more

**Comment by YiJingMolly** [comment]
In my understand ,the architecture in your paper 
the encoder use Resnet50 is like the figure 2. (top) of flownet
the decoder is like Figure 3. of flownet
Is it ?
Thank you for this detailed reply.

**Comment by mrharicot** [comment]
We tried two encoders, vgg-like and resnet50.
The decoder is indeed similar to flownet and dispnet

**Comment by tabarkarajab** [comment]
hi, can you elaborate on the architecture you use for monodepth?
