### ISSUE TITLE
Flipped image at test time

### ISSUE THREAD

**Issue by alwynmathew** [mrharicot/monodepth#159]
Why do you take `left_image_o` and `tf.image.flip_left_right(left_image_o)` as a batch at test time? Why dont you just use `left_image_o` as input at test?

https://github.com/mrharicot/monodepth/blob/master/monodepth_dataloader.py#L67

**Comment by mrharicot** [comment]
Hi,
This is for the post-processing step, described in Section 4.1 of the paper:
https://arxiv.org/pdf/1609.03677.pdf
