### ISSUE TITLE
Possibly incorrect Kitti evaluation of the model trained on Cityscapes

### ISSUE THREAD

**Issue by sebastianbujwid** [mrharicot/monodepth#160]
Hi,

I'm a bit concerned about the correctness of the script that I suppose was used for evaluation on Kitti, that is `utils/evaluate_kitti.py`. I tried this script on Cityscapes model snapshot that you provide and the errors I get match the numbers that you show in the paper for this model, in Table 1. So this makes me confident that this is how you obtained those numbers.

But in my opinion, `utils/evaluate_kitti.py` converts disparities into depth in a way that I don't think is correct.
The model trained on Cityscapes produces disparities which correspond to an image shifted by something around 0.22m (baseline), so no matter what image you input in the test time, the correct conversion to depth should use the baseline that was used during training time. But for some reason (I guess just a bug…?) `utils/evaluate_kitti.py` script has hardcoded baseline set to 0.54 m (Kitti). I don't see a reason why baseline on the dataset you evaluate on would matter…
In fact when I run the evaluation with Cityscapes baseline, the errors are less then a half of what you show in the paper, that is:
>   abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
>    0.3284,     2.2720,      7.500,      0.442,     91.487,      0.136,      0.660,      0.937

Another concerning thing that I found, is that the Cityscapes images have the bottom cropped (to get rid of the hood) and resized after to 512x256 resolution. Because the target resolution has a different aspect ratio, the images (after cropping) are stretched during resizing, which makes everything wider in this case. This operation scales corresponding disparities proportionally, so whenever the estimated disparities are converted into depth values, they should be compensated for this operation. In effect, the disparities that are being produced by the model correspond to the transformed (stretched) image.

Because of these two factors that I mentioned, to me it seems like the numbers that you show in the paper are incorrect and the errors should be much lower.
I'd like to hear from you about what do you think about these two issues :)
But I'm afraid that in this case the paper might draw misleading conclusions, because it seems like the model trained on just Cityscapes works much better on Kitti

**Comment by mrharicot** [comment]
Hi,

Indeed the cityscapes evaluation wasn't properly thought out at the time. This isn't a bug. The results are likely better if you use the baseline *and focal* of cityscapes.
However even when doing so, the results are still worse than when trained on KITTI, which is expected.

Images are stretched no matter if you crop the car hood or not, we train with a 2x1 ratio but kitti is originally 3.3x1.
There is no need to take reshaping into account as the disparities are expressed relative to the image width, moreover the stretch is vertical here.

What conclusions did you think were misleading?
I think we meant to say that there is ambiguity when converting disparities into depths when testing on images from a different dataset. 
What should you do if you test on an image that has a focal length twice as large? or an aspect ratio quite different?
You can consider the depthmaps to be reasonable "up to scale". This is why [Zhou](https://github.com/tinghuiz/SfMLearner/) aligns the medians of the predicted depthmaps to the groundtruth for evaluation.

**Comment by yhfeng1995** [comment]
Hi,

Thanks for your answer. Does that mean, if I test on a mono camera, the focal or the aspect ratio of which is different with those of training set, to get the exact depth, I should calculate with the focal of my mono camera and the baseline of training set?

**Comment by mrharicot** [comment]
Hi @yhfeng1995,
This is where it is unclear you can just assume that you have a scaled inverse depth and try to find the scale manually.
