### ISSUE TITLE
clip_by_value

### ISSUE THREAD

**Issue by Yc174** [mrharicot/monodepth#161]
Dear author:
       I have read your code and these are really fantastic! Although I still have some problems about these. Can you tell me why use tf.clip_by_value in augmentation? I mean this operation will not make data confusion？  Thanks. @mrharicot

**Comment by mrharicot** [comment]
Hi,
I think I did that with the idea that that would prevent the network to be able to identify augmented images (because their range could leave 0-1).
I actually have no idea whether it works better with or without :)
