### ISSUE TITLE
get_disparity_smoothness broadcast error

### ISSUE THREAD

**Issue by alwynmathew** [mrharicot/monodepth#163]
At [get_disparity_smoothness](https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L109) function:

If size of `disp` is Bx256x512x1, the output of `self.gradient_x(disp)` will be Bx256x511x1 and `self.gradient_y(disp)` will be Bx255x512x1. 
```
def gradient_x(self, img):
        gx = img[:,:,:-1,:] - img[:,:,1:,:]
return gx

def gradient_y(self, img):
        gy = img[:,:-1,:,:] - img[:,1:,:,:]
return gy
```
Thus size of `smoothness_x` and `smoothness_y` will be Bx256x511x1 and Bx255x512x1 respectively which cant be [added directly](https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L121) without matching the size of the tensors.

**Comment by mrharicot** [comment]
Hi,
This is a known issue, see [issue 46](https://github.com/mrharicot/monodepth/issues/46).
