### ISSUE TITLE
How to obtain the ground truth disparities?

### ISSUE THREAD

**Issue by hawjnsafdjlk** [mrharicot/monodepth#164]
Hi, dear author, you also posted ground truth disparities in your paper, but your method is unsupervised. how did you get the ground truth disparities you posted?

**Comment by mrharicot** [comment]
Hi,
Please have a look at the evaluation code where we either load the disparities or reproject the lidar point clouds:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluate_kitti.py
