### ISSUE TITLE
Question about "Digging Into Self-Supervised Monocular Depth Estimation"

### ISSUE THREAD

**Issue by a-jahani** [mrharicot/monodepth#167]
I was wondering if your network output for "self-supervised Stereo Training" is disparity or inverse depth?

"With known focal length and camera baseline the predicted disparity map, i.e. the inverse depth
map, can then be converted into scaled metric depth"

Thanks

**Comment by mrharicot** [comment]
Hi,

The network outputs `disp` through a sigmoid, which is then turned into a depth through:
```python
min_disp = 1 / max_depth
max_disp = 1 / min_depth
scaled_disp = min_disp + (max_disp - min_disp) * disp
depth = 1 / scaled_disp
```
Where we used max_depth = 100 and min_depth = 0.1

I hope this helps!

**Comment by daniyar-niantic** [comment]
@a-jahani The implementation is now public at https://github.com/nianticlabs/monodepth2
