### ISSUE TITLE
Evaluation on KITTI split is not good as your result

### ISSUE THREAD

**Issue by jeongc** [mrharicot/monodepth#17]
Hi 
First of all, I like to thank for sharing your wonderful works. But I have some things to be cleared.

The file "utils/filenames/kitti_test_files.txt" contains 12223 test samples, and when I ran inference 
using your pretrained weight, which I named as "vgg_pretrained" as follows:

python monodepth_main.py --mode test --data_path ~/tf/data/kitti/ --output_directory ~/tf/data/monodepth/my_run/vgg_pretrained/result --filenames_file utils/filenames/kitti_test_files.txt --log_directory tmp/ --checkpoint_path ~/tf/data/monodepth/my_run/vgg_pretrained/model/kitti/model_kitti

This inference test generated almost 6GiB disparities.npy. After that, I ran your evaluation script as:

python utils/evaluate_kitti.py --split kitti --predicted_disp_path ~/tf/data/monodepth/my_run/vgg_pretrained/result/disparities.npy --gt_path ~/tf/data/kitti/

But I got  a quite different result and the evaluation script only check the first 200 samples:

abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
0.3232,     5.2624,     10.887,      0.498,     61.258,      0.547,      0.710,      0.822

By the way, when I ran the evaluation on your KITTI disparities.npy(~100MiB), which I downloaded:

python utils/evaluate_kitti.py --split kitti --predicted_disp_path ~/tf/data/monodepth/ref/vgg/result/disparities.npy --gt_path ~/tf/data/kitti/

I got the same result as Table 1 in your paper.
abs_rel,     sq_rel,        rms,    log_rms,     d1_all,         a1,         a2,         a3
0.1235,     1.3882,      6.125,      0.217,     30.272,      0.841,      0.936,      0.975

But I don't know why you just evaluated only on 200 samples, and your disparities.npy file contains also only 200 samples, but "utils/filenames/kitti_test_files.txt" contains 12223 test samples.
I think the evaluation result might be different due to this issue. Let me know why check on all 12223 samples, and could I get your full file (disparity.npy) for that?
Thanks in advance.

CJ

**Comment by mrharicot** [comment]
Hi CJ,

As you can read in the paper, we tested the model on two different splits, if you want to test like the paper on `kitti` you need to use `kitti_stereo_2015_test_files.txt`.
You will then have the same results.

We created this split to be able to test on the high quality disparity maps in the kitti 2015 stereo dataset, please see section 4.2 in our [paper](https://arxiv.org/pdf/1609.03677.pdf).

Clément

**Comment by jeongc** [comment]
Hi Clement,

You are right. I missed that point. I got the same result as yours.
Thanks.

CJ
