### ISSUE TITLE
Newer versions of code

### ISSUE THREAD

**Issue by varun19299** [mrharicot/monodepth#174]
Thank you for the tf implementation, we've found it quite useful.

However, the repo seems not updated from changes that have occurred since Nov 2017 in` tf` (better IO pipelines, Estimators, visualisation).

We've used these modifications to distribute training and add more feature extractors. 

Are there any plans to continue support for this repo? In which case, would a pull request be accepted?

**Comment by mrharicot** [comment]
Hi,

I will still support this repo for bug-fixing only but won't be updating it to the more recent API to simplify maintenance.
At some point in the future we'll release the code of our [new method](https://arxiv.org/abs/1806.01260) as it's simpler to modify and produces significantly better results in less time.

**Comment by mrharicot** [comment]
[monodepth 2](https://arxiv.org/abs/1806.01260) is indeed more recent than this paper. We did compare with it as well as with all the cvpr 2018 papers doing depth estimation.
