### ISSUE TITLE
input shape and testing

### ISSUE THREAD

**Issue by Sparkkkk** [mrharicot/monodepth#175]
Hi,

I am curious about the input shape 256, 512.  I have changed the some different value, and the output is very different. Is the best value you choose or it can be random multiple of 64?

Also, I don't understand why do you flip the image before pass to the network. Does it means you also do that during training phase.

Thirdly, am I able to pass 1000 images to the network at a time?

**Comment by mrharicot** [comment]
Hi,

The network was trained with 256x512 so if you feed anything different the behaviour is unclear.
You can however train with any multiples of 128 for vgg and 64 for the resnet (iirc).

The flipping is only used for test time post-processing.

Unsure what you mean by 1000 images at a time? The only limit should be memory then.

**Comment by Sparkkkk** [comment]
Thanks for your reply! 

I have a large image dataset and want to do an anti spoofing task. So my idea is using your network as a pre-pocessing stage to detect the depth of image. Then the output will be the input of my network.

Since I want to get the benefit of vectorization to increase the speed of pre-pocessing instead of running a for loop to iterate each image at a time, so I wonder if I can process multiple images at a time to your model. 

Also without flipping, do you think I can still get useful information about depth of original image?

**Comment by mrharicot** [comment]
I am not sure the output of this network will be particularly useful for your task.
You might want to use a pre-trained imagenet model instead as it will be more general.

You can feed a batch of any size at test time, as long as memory isn't an issue.

You don't need the flipping, it was just a nice addition to improve scores.
