### ISSUE TITLE
can't download pre-made models

### ISSUE THREAD

**Issue by shokah** [mrharicot/monodepth#178]
hi,

I tried to download the models using your instructions but i get a message they cant be found.

i also tried to get into the link with the .sh leads to and i get the same result

**Comment by mrharicot** [comment]
Hi,
They seem to be working fine right now.
Do they work on your end?
UCL's servers are down once in a while.

**Comment by shokah** [comment]
worked. 

tnx

**Comment by mrharicot** [comment]
Hi,
Are you under windows? I haven’t tested the scripts for windows.
You can simply unzip it manually.
