### ISSUE TITLE
Error "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

### ISSUE THREAD

**Issue by aquatom** [mrharicot/monodepth#179]
Hi, 

I keep getting the following error when training the model (please note that the code works and the model is actually training). I also get decent results!  

```
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
```

Specs:
- tensorflow-gpu==1.8.0 (same error with 1.0)

I am running the model on GTX 1080 ti, in a docker container. 

I tripled check my file path / format / ability to open them with PIL - opencv. The images are quite big (4K) but even when resizing them, I get the same error. When training on input size of 1024 by 1024, I get less than one image per second. 256x512, I have an average of 12 images processed per seconds.

**Comment by mrharicot** [comment]
Hi,

This is not an error, just a warning. 
It has always been here.
I never bothered figuring out where it came from as the training speed seemed fine.
