### ISSUE TITLE
question on monocular depth

### ISSUE THREAD

**Issue by B-Betty** [mrharicot/monodepth#180]
Dear Author,
you work is to obtain the depth estimation in single images based on training with binocular stereo footage.
I wonder  how can i get the baseline in the following function， if I test images obtaining from another Monocular camera  instead of  binocular stereo footage obtaining images for training ??
Is the baseline belonging to the baseline in  binocular stereo footage??
              depth = baseline * focal / disparity
thanks very much

**Comment by mrharicot** [comment]
Hi,
As mentioned in previous issues, there is no clear way to convert the disparities to depth in the case of a different test camera.
You can assume it will be correct up to some scale.

**Comment by UannaFF** [comment]
Hello, i also want to test with an image from an RGB camera, but I have the same question about the baseline. Did you find an answer to this? @B-Betty
