### ISSUE TITLE
How to freeze model?

### ISSUE THREAD

**Issue by gi097** [mrharicot/monodepth#181]
Hello,

I downloaded your pretrained cityscapes model. The files contained in there are:
- model_cityscapes.meta
- model_cityscapes.index
- model_cityscapes.data-00000-of-00001

I did like to freeze the graph to a frozen `.pb` file.  So I am using this script to load and freeze the model:

```python
import tensorflow as tf

meta_path = 'model_cityscapes.meta' 
output_node_names = ['output:0']

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path)

    # Load weights
    saver.restore(sess,tf.train.latest_checkpoint('.'))

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
      f.write(frozen_graph_def.SerializeToString())
```

However, since your provided files do not include any `checkpoint`, the following line raises an error:
`tf.train.latest_checkpoint('.')`, it returns `None`.

Could you explain how to correctly freeze this model?

**Comment by gi097** [comment]
I was able to load the graph using:

```python
import tensorflow as tf

meta_path = 'model_cityscapes.meta'
output_node_names = ['output:0']

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path, clear_devices=True)

    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    sess = tf.Session()
    saver.restore(sess, "model_cityscapes")
```

**Comment by yuli1994** [comment]
> I have trouble finding the output node name of this model. Do you know the name?

Hi,I got this problem too.Do you know the output_node now?
Thanks
