### ISSUE TITLE
Question on KITTI depth prediction benchmark

### ISSUE THREAD

**Issue by e2sh83** [mrharicot/monodepth#183]
@mrharicot 
Thanks for your share.
I have a question on the score of KITTI depth prediction benchmark. I ran your VGG based KITTI model with the test images downloaded from KITTI depth prediction. Unexpected low level of benchmark score is founded like below:
   SILog: 43.97, sqErrorRel: 49.58, absErrorRel: 56.02, iRMSE: 254.93
I basically utilize "monodepth_simple.py" file with some modification such as forcing no pixel larger than 80, and save 16bit png type after multiply 256 to all pixel value.
Do you have any idea or comment what is wrong here?

**Comment by mrharicot** [comment]
Hi,
Do the depthmaps look fine?
Are you trying to use the new single frame depth benchmark?
If so two remarks:
The pretrained networks are trained on a split which might include some of the test images, you cannot use these models.
I believe this benchmark expects depth in meters, while monodepth simple produces normalized disparities.
Have a look at [our evaluation code](https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py) to convert disparities to depth.

**Comment by e2sh83** [comment]
@mrharicot 
Thanks for your answer.
I forgot to mention that conversion from disparity to distance is also made with the formula "depth = 0.54 * 721 / (original_width * disp_pp)"
I will check your code out.
