### ISSUE TITLE
Color encoding of depth images

### ISSUE THREAD

**Issue by marcel1991** [mrharicot/monodepth#184]
I am wondering how you implemented the color encoding of depth values in the depth images. Basically the transition from yellow to red to blue for increasing depth.

Is there any script or where did you get this color encoding from?

**Comment by marcel1991** [comment]
Hm okay. And then you inverted the depth and normalized it to a [0,1] range, like

``1 - depth/depth.max()``

? Or did you use the inverse depth? Did you also clamp to a max depth?

Because my images look way more yellow at near distances than yours.

**Comment by mrharicot** [comment]
Hi,
We the normalized disparities, essentially the raw output of the network, and use the same fixed range for all disparity maps:
vmin=0 and vmax=0.06 for KITTI and vmax=0.04 for Cityscapes

**Comment by marcel1991** [comment]
Okay thank you!
