### ISSUE TITLE
some velodyne of kitti split is missing 

### ISSUE THREAD

**Issue by dyz-zju** [mrharicot/monodepth#186]
I want to get the corresponding depth from velodyne as eigen split or kitti split.
you provide the test file lists of kitti split in [filenames](https://github.com/mrharicot/monodepth/blob/master/utils/filenames/kitti_test_files.txt),
but I could't get some velodyne which is missing in the raw data. for example,
2016_09_26_drive_0009_sync，we could get its left image and right image for all sequence，but the corresponding velodyne of 177-180 is missing. I need these data to get depth map，could you please check it and share for me. Thanks a lot.

**Comment by mrharicot** [comment]
Hi,
kitti_test_files.txt is actually not used so this shouldn't be a problem.
some velodyne files are missing indeed, but it should not be a problem for training or testing
