### ISSUE TITLE
make3D evaluation

### ISSUE THREAD

**Issue by a-jahani** [mrharicot/monodepth#189]
Once again thank you for your code.

I'm trying to replicate your result on make3D dataset but so far the result I'm getting is different than your reported numbers (I'm getting RMSE around 15 meter ish).

In [Issue1 ](https://github.com/mrharicot/monodepth/issues/104#issuecomment-372031726) you said you cropped to the ratio of 2.5:1  (same ratio as the cityscape after cropping the carhood).
In [Issue2](https://github.com/mrharicot/monodepth/issues/154#issuecomment-393865771) you said you cropped to the ratio of 2:1 . 

I was wondering which one is correct.
Which cityscape model is used? Resnet50 or VGG?

Thank you

**Comment by mrharicot** [comment]
Hi,

Issue 2 is the correct one, and we used the resnet model iirc.

I hope this helps

**Comment by mrharicot** [comment]
Here is the code we used for monodepth2:

```python

def compute_errors(gt, pred):
    rmse = (gt - pred) ** 2
    rmse = np.sqrt(rmse.mean())

    rmse_log = (np.log10(gt) - np.log10(pred)) ** 2
    rmse_log = np.sqrt(rmse_log.mean())

    abs_rel = np.mean(np.abs(gt - pred) / gt)

    sq_rel = np.mean(((gt - pred)**2) / gt)

    return abs_rel, sq_rel, rmse, rmse_log


with open(os.path.join(main_path, "make3d_test_files.txt")) as f:
    test_filenames = f.read().splitlines()
test_filenames = map(lambda x: x[4:-4], test_filenames)


depths_gt = []
images = []
ratio = 2
h_ratio = 1 / (1.33333 * ratio)
color_new_height = 1704 / 2
depth_new_height = 21
for filename in test_filenames:
    mat = scipy.io.loadmat(os.path.join(main_path, "Gridlaserdata", "depth_sph_corr-{}.mat".format(filename)))
    depths_gt.append(mat["Position3DGrid"][:,:,3])
    
    image = cv2.imread(os.path.join(main_path, "Test134", "img-{}.jpg".format(filename)))
    image = image[ (2272 - color_new_height)/2:(2272 + color_new_height)/2,:]
    images.append(image[:,:,::-1])
    cv2.imwrite(os.path.join(main_path, "Test134_cropped", "img-{}.jpg".format(filename)), image)
depths_gt_resized = map(lambda x: cv2.resize(x, (305, 407), interpolation=cv2.INTER_NEAREST), depths_gt)
depths_gt_cropped = map(lambda x: x[(55 - 21)/2:(55 + 21)/2], depths_gt)

pred_disps = np.load(path_to_pred_disps)

errors = []
for i in range(len(test_filenames)):
    depth_gt = depths_gt_cropped[i]
    depth_pred = 1 / pred_disps[i]
    depth_pred = cv2.resize(depth_pred, depth_gt.shape[::-1], interpolation=cv2.INTER_NEAREST)
    mask = np.logical_and(depth_gt > 0, depth_gt < 70)
    depth_gt = depth_gt[mask]
    depth_pred = depth_pred[mask]
    depth_pred *= np.median(depth_gt) / np.median(depth_pred)
    depth_pred[depth_pred > 70] = 70
    errors.append(compute_errors(depth_gt, depth_pred))
mean_errors = np.mean(errors, 0)

print(("{:>8} | " * 4).format( "abs_rel", "sq_rel", "rmse", "rmse_log"))
print(("{: 8.3f} , " * 4).format(*mean_errors.tolist()))

```

**Comment by a-jahani** [comment]
Thanks for sharing your code! It helped me understand it more! 
I didn't know scaling was done for Make3D evaluation! So you are forcing the medians of gt and prediction to be equal ` depth_pred *= np.median(depth_gt) / np.median(depth_pred)` .
One different I noticed here is you are calculating the error on all pixels(making pixels more than 70m to be 70 and accounting 0 error for them) vs in kitti or eigen evaluation it has been done over masked ones.
In Make3D: `compute_errors(depth_gt, depth_pred)`
In eigen and Kitti: `compute_errors(gt_depth[mask], pred_depth[mask])`

This will definitely lower the mean error for Make3D cause of adding more points with 0 error! I was just wondering if it was better to use mask for both or not use mask for both?

**Comment by mrharicot** [comment]
The median scaling was first used by Zhou and should only be used if you are **not** training with stereo data.

> One difference I noticed here is that you are calculating the error on all pixels

We are also masking pixels here in this code:
```python
depth_gt = depth_gt[mask]
depth_pred = depth_pred[mask]
```
Or did I miss something?

**Comment by a-jahani** [comment]
My bad. that's correct! 
Another thing I noticed and was wondering if you are aware that in your training of cityscape dataset, the camera has a different baseline/focal length within the different sequences.

**Comment by mrharicot** [comment]
It is actually already the case with KITTI, they are all slightly different. I never took that into account for Make3D as the quality of the ground truth is so bad anyway that it shouldn't really impact the results.

**Comment by a-jahani** [comment]
Yeah!
Thanks for your quick reply.
