### ISSUE TITLE
How feed images to model

### ISSUE THREAD

**Issue by enigmanx** [mrharicot/monodepth#19]
Hi
I try to use your models in my project. So, maybe you can share easy way to feed images to model and get estimation. I loaded graph and model and it seems that i need to get tensor by name and feed images in some format. 
Sorry, I can not debug project because downloading kitti takes too much time.
Thx

**Comment by mrharicot** [comment]
Hi,

Without modifying any code the easiest way is to use a placeholder and pass it as a parameter to the network when you create it.
You can then run using a feed_dict.
You can find some examples [here](https://www.tensorflow.org/get_started/mnist/mechanics)
