### ISSUE TITLE
Question about "Digging into Self-Supervised Monocular Depth Estimation"

### ISSUE THREAD

**Issue by zieitokk** [mrharicot/monodepth#193]
Hi, 
I have a question about the process in the pose network. The pose network takes time sequence images as inputs and those images are separately distributed into three encoder network. So my question is that how do we use dataset Like KITTI as the inputs of pose network? And how do we implement the pose network?

Thank you very much!

**Comment by mrharicot** [comment]
Hi,
Apologies for the massive delay.
You essentially need to run the encoder 3 times for each image, then concatenate the features produced.
The code will be available soon, we'll put a link into the monodepth readme

**Comment by daniyar-niantic** [comment]
@zieitokk The implementation is now public at https://github.com/nianticlabs/monodepth2
