### ISSUE TITLE
model

### ISSUE THREAD

**Issue by liuhengli** [mrharicot/monodepth#2]
I'm sorry if I troubled you. I want to know your pre-train model is mono or stereo.think you !!! I see your code '--do_stereo' is defult true.

**Comment by mrharicot** [comment]
Hi,

The model can do both, and will be mono by default.
If you want to train a stereo model, just use `--do_stereo`.
The `do_stereo` option is only set to `True` if used, otherwise it defaults to `False`.
See [argsparse's documentation](https://docs.python.org/2/library/argparse.html#action).

**Comment by liuhengli** [comment]
Thank you very much! I want to know your version of tensorflow

**Comment by mrharicot** [comment]
The code was written for Tensorflow 1.0 and also works on 1.0.1
