### ISSUE TITLE
Why the tensor shape of self.disp1 = (4,?,?,16)

### ISSUE THREAD

**Issue by lixiangyu-1008** [mrharicot/monodepth#200]
hi @mrharicot 
I want to use the shape of all the 4 disp, but the disp1' tensor shape was (4,?,?,16)

**Comment by mrharicot** [comment]
Hi,
I am not quite sure I understand what your problem is.
Could you please clarify?

**Comment by lixiangyu-1008** [comment]
hi , 
I use  pycharm to run the code. I would like to watch the shape of  4  scale disparity output from the dispNet. so I set a breakpoint. as I know , when the code run stop at the breakpoint , we can see the tensor shape. but when I run your code, I found the 4 scale disparity , disp1,disp2,disp3 disp4 .only the disp1's tensor shape is (4,?,?,2),the other 3 was (4,128,256,2) (4,64,128,2) and (4,32,64,2). Do you know why?

**Comment by mrharicot** [comment]
When you put a pycharm breakpoint you are stopping the code when it is creating the graph, tensorflow doesn't always need to know the sizes to build the graph and can pass a "?" instead

**Comment by lixiangyu-1008** [comment]
Thank you for reply!
