### ISSUE TITLE
how can I read the real distance from monodepth_simple.py

### ISSUE THREAD

**Issue by RichardYao1995** [mrharicot/monodepth#216]
I use a trained model to predict the distance of an input image. In the code monodepth.py, which value shows the real distance of an image, or how can I calculate the real distance?
Thanks very much.

**Comment by codermckee** [comment]
@RichardYao1995 HI, do you know how to get the real distance now??

**Comment by RichardYao1995** [comment]
> @RichardYao1995 HI, do you know how to get the real distance now??

https://github.com/mrharicot/monodepth/issues/49#issuecomment-330595397

**Comment by ShoaibSajid** [comment]
@RichardYao1995 @codermckee 
What is the value of baseline you are using to find distance when using a single camera setup?
