### ISSUE TITLE
Model about stereo version

### ISSUE THREAD

**Issue by Aryayay** [mrharicot/monodepth#22]
In your paper you said that you also implemented a stereo version of your model. Your test results has showed that stereo version improved the D1-all disparity measure.

But you also said that "This model was only trained for 12 epochs as it becomes unstable if trained for longer", Wht this happened?

if I want train my own model use my own training data(indoor scenes) with stereo version model, Do I need to change your source code?

If we only concern the D1-err, stereo version model  similar with the traditional stereo matching algorithm named "elas", it means that this depth estimation method can be used to some practical applications

**Comment by mrharicot** [comment]
Hi,

I did not figure out why the stereo model became unstable.
It never happened in our previous Torch implementation.

The only real change between both versions comes from the implementation of the bilinear sampler and the deconvolutions which have been replaced with resize-convolutions.

You could also try adding some regularization to the network and see if it helps.

**Comment by mrharicot** [comment]
Hi,

I am not quite sure of what you mean by "the disparity exist only when the stereo image pairs existed".

If you test on images which have a different focal length the result will probably be less accurate.
However you can fine-tune a pretrained on data with a different baseline, which is what we did in the paper. You could also possibly mix both datasets, however it might be confusing for the network as the same depth will result in a different disparity. I suspect that the network would overfit and learn to identify which dataset the image is from.

**Comment by Aryayay** [comment]
Hi,

By "the disparity exist only when the stereo image pairs existed" , I means that disparity exist only when scene is imaged more than one viewpoint, and may be different if the position changed betweent different viewpoint.
So , I think the main Limitations of your methods is cannot used to different cameras. 

Another question,  I did not recurrence results of stereo model in your paper, can you tell me the params setting when you are training the stereo model?

thanks a lot!

**Comment by mrharicot** [comment]
Indeed the current model only supports one camera at a time, nothing is stopping it from learning from different cameras/baseline at the same time but I predict the results won't be great.

The stereo model was trained with the exact same parameters as the mono version.
We found out that the model became unstable after ~12 epochs, which somehow did not happen in our previous Torch implementation. We thus stop training after 12 epochs.

**Comment by JackHenry1992** [comment]
Hi, @mrharicot  , I also want to evaluate this method for indoor scenes, can you provide some pretrained model and datasets for indoor scenes . 
@Aryayay , can you share your results in indoor_scenes predicted by monodepth?
It will be very grateful if you can upload your indoor_dataset, cause I can not find suitable stereo indoor dataset.

**Comment by mrharicot** [comment]
I do not have models nor datasets to share for indoor stereo unfortunately.

**Comment by Aryayay** [comment]
@JackHenry1992 , my indoor dataset is quiet simple, just use a stereo camera and capture some video.

**Comment by Aryayay** [comment]
@mrharicot ,  I found another unsupervised method in here<https://github.com/tinghuiz/SfMLearner>. and he also use dispnet network, and i  solved the stereo model training problem according to this method.
