### ISSUE TITLE
Bad results while training on EuRoC dataset

### ISSUE THREAD

**Issue by Beniko95J** [mrharicot/monodepth#234]
Hi, I would like to train your monodepth model on the EuRoC Machine Hall dataset, which is more difficult than the KITTI dataset. I have previously stereo rectify the images for training, but the trained result is not good. In fact, the loss is fluctuating. Here is the last part of training logs:

![Screenshot from 2019-07-23 14-38-02](https://user-images.githubusercontent.com/30772597/61685374-82385280-ad57-11e9-878b-dbc505bc24d0.png)

I have tested the trained model on a single image, and as expected it does not work properly:

![1](https://user-images.githubusercontent.com/30772597/61685614-3c2fbe80-ad58-11e9-9a42-58502a9e2750.jpg)
![1_disp](https://user-images.githubusercontent.com/30772597/61685499-e5c28000-ad57-11e9-83fa-ec312769b316.png)

Is there any suggestion about training monodepth model on such a difficult dataset? Thanks!

**Comment by mrharicot** [comment]
Hi,
Can you share a few examples of the stereo rectified images?

**Comment by Beniko95J** [comment]
Thank you for your reply!

Here are some examples of my stereo rectified images, in fact I found they have a very short baseline:

1. 
![1403636734763555584_left](https://user-images.githubusercontent.com/30772597/61940693-ef0a5180-afd0-11e9-9451-293c080203aa.jpg)
![1403636734763555584_right](https://user-images.githubusercontent.com/30772597/61940701-f29dd880-afd0-11e9-87d4-dc342a2265d4.jpg)

2.
![1403636987151666432_left](https://user-images.githubusercontent.com/30772597/61940999-8f607600-afd1-11e9-80d4-c23f7044c9d7.jpg)
![1403636987151666432_right](https://user-images.githubusercontent.com/30772597/61941007-95565700-afd1-11e9-9a5e-c57bb3343b72.jpg)

**Comment by mrharicot** [comment]
Hi,
These images are not rectified. monodepth assumes rectified images and will not work otherwise.
Things should only move _horizontally_ between rectified images.

**Comment by Beniko95J** [comment]
You are right. After I checked and modified my codes, I get a relatively good result. Thank you very much!

![1](https://user-images.githubusercontent.com/30772597/62001525-6d7c0600-b12d-11e9-8855-0d1fb36b1877.jpg)
![1_disp](https://user-images.githubusercontent.com/30772597/62001526-6fde6000-b12d-11e9-8e1b-459617faff44.png)

By the way, may I ask what is the difference between model-40000 and model-71600 in my log directory? The prediction from these two models are quite similar.

![Screenshot from 2019-07-28 11-48-49](https://user-images.githubusercontent.com/30772597/62001546-feeb7800-b12d-11e9-80fd-a3d00e4b7d3d.png)

Thanks!

**Comment by zaher88abd** [comment]
Hi @Beniko95J, may I ask you How many images you used to train the model?
