### ISSUE TITLE
disagreement between the model in code and the model descripted in paper ?

### ISSUE THREAD

**Issue by jasonTuZq** [mrharicot/monodepth#24]
Hi,
according to 'encoder' part of the model descripted in your paper,
 i think conv_block in the code should be,
    def conv_block(self, x, num_out_layers, kernel_size):
        conv1 = self.conv(x,     num_out_layers, kernel_size, 2)
        conv2 = self.conv(conv1, num_out_layers, kernel_size, 1)
        return conv2
instead of
    def conv_block(self, x, num_out_layers, kernel_size):
        conv1 = self.conv(x,     num_out_layers, kernel_size, 1)
        conv2 = self.conv(conv1, num_out_layers, kernel_size, 2)
        return conv2
Am i understanding your paper or code right ?
Looking forward to your response. Thanks !

**Comment by mrharicot** [comment]
Hi,

Indeed there was a typo in the model description in the paper.
I will update the arXiv at some point.

It shouldn't matter too much, it's a small speed/accuracy tradeoff.

Thanks for spotting it!
