### ISSUE TITLE
It seems the input not do normalization?

### ISSUE THREAD

**Issue by cswwp** [mrharicot/monodepth#242]
It seems the input not do normalization? why?

![image](https://user-images.githubusercontent.com/11901683/75509873-07899100-5a24-11ea-94b1-c4a57aea684f.png)

**Comment by sieme97** [comment]
See the read image function. The following line normalizes the input images:
image  = tf.image.convert_image_dtype(image,  tf.float32)

**Comment by cswwp** [comment]
> See the read image function. The following line normalizes the input images:
> image = tf.image.convert_image_dtype(image, tf.float32)

Thanks for reply, i got it
