### ISSUE TITLE
disparity map error

### ISSUE THREAD

**Issue by YunYang1994** [mrharicot/monodepth#244]
hi, thanks for your impressive work, which helps me a lot. but I met the following problem and I have no idea about it. Can you give me some points to solve it ?

![0000000012](https://user-images.githubusercontent.com/30433053/76438366-dd59ab00-63f5-11ea-8cc9-61ed50611dc8.jpg)

thanks in advance!

**Comment by sieme97** [comment]
Apply post-processsing.
