### ISSUE TITLE
Not able to recreate the results

### ISSUE THREAD

**Issue by aqeelanwar** [mrharicot/monodepth#25]
Hello,
I tried running the code to generate the disparity maps for the images you reported in your paper. The code runs without any error, but when I plot the generated disparity maps, they are nothing like the ones you reported. Am i missing something?

**Comment by mrharicot** [comment]
Hi,
Can you please give me a bit more to work with?
What command did you run exactly?

**Comment by aqeelanwar** [comment]
I appreciate the quick response.
I ran the following

python monodepth_main.py --mode test  --filenames_file utils/filenames/test.txt --log_directory ~/tmp/ --data_path data

I realized nowhere I am referencing the trained model that I downloaded (model_cityscapes). Where exactly do i reference it?

**Comment by mrharicot** [comment]
You indeed forgot to reference the checkpoint to load.
Please look at the readme page, everything is explained.

**Comment by aqeelanwar** [comment]
My bad. Thank you for clearing it out.
I am able to generate the results now.

**Comment by mrharicot** [comment]
I added a comment on the readme to remind people to load the model too :)
