### ISSUE TITLE
About the kitti weight in kitti_archives_to_download.txt

### ISSUE THREAD

**Issue by liuhe1305** [mrharicot/monodepth#250]
Hi, could kindly tell me if the entire dataset in the list of kitti_archives_to_download totally weights about 175GB? Why did I download all 66 items in kitti_archives_to_download.txt and unzip them but only totally weights about 163.8GB? Am I lost some dataset?
Thanks!

**Comment by mrharicot** [comment]
Hi,
I think there isn't a problem, OS count GB in different ways.
It seems that your OS is counting 163.8GiB, which is 175.9GB.
https://docs.ukcloud.com/articles/other/other-ref-gib.html

I hope this helps!

**Comment by liuhe1305** [comment]
> Hi,
> I think there isn't a problem, OS count GB in different ways.
> It seems that your OS is counting 163.8GiB, which is 175.9GB.
> https://docs.ukcloud.com/articles/other/other-ref-gib.html
> 
> I hope this helps!

Got it! Thanks a lot!

**Comment by liuhe1305** [comment]
Got it! Thanks a lot!
