### ISSUE TITLE
Load ImageNet weights for ResNet50

### ISSUE THREAD

**Issue by indhu26** [mrharicot/monodepth#251]
Hi,
I am trying to load imagenet pretrained weights for resnet50 for training.

@mrharicot Can you point me to the weights that you used for training or can we just import from keras.application.resnet

**Comment by mrharicot** [comment]
Hi,
monodepth1 does not use pretrained weights but [monodepth2](https://github.com/nianticlabs/monodepth2/) does!

Hope this helps!

**Comment by indhu26** [comment]
Thank you so much for the quick response.
@mrharicot  Can you say the difference between monodepth1 and monodepth2 ?

Thanks in advance.
