### ISSUE TITLE
Video as input

### ISSUE THREAD

**Issue by aqeelanwar** [mrharicot/monodepth#26]
Hi,
I was trying to understand the way you structured your code.
After having a careful look at your code, it seems that your code is structured in a way that it accepts all the test images (their names in filenames) at once during the call of 
`dataloader = MonodepthDataloader(args.data_path, args.filenames_file, params, args.dataset, args.mode)` 
Then based on the loaded data files, you load the model using
` model = MonodepthModel(params, args.mode, left, right)`
Finally when you run the session, I assume it gets the image using the filename and generates the output. 
I dont really get what exactly `model.disp_left_est[0]` denotes in the call ` = sess.run(model.disp_left_est[0])`
Can you please help me understand the structure of the code for mode=test.

I want to modify the code to receive video as input and generate disparity video as output using Moviepy. Understanding the code structure will really help me in this regard. Thank you

**Comment by aqeelanwar** [comment]
Here is what I am doing.
I have replaced the following commands
`dataloader = MonodepthDataloader(args.data_path, args.filenames_file, params, args.dataset, args.mode)
    left  = dataloader.left_image_batch
    right = dataloader.right_image_batch`
with a placeholder for left and right
` left = tf.placeholder(tf.float32, [2,256,512,3])
   right = tf.placeholder(tf.float32, [2, 256, 512])`
the model was then created based on these placeholders
`model = MonodepthModel(params, args.mode, left, right)`

The left placeholer was initialized with teh test image as follows
` image = cv2.imread("data/challenge01.jpg")
    left1 = tf.image.resize_images(image, [256, 512])
    leftp = tf.stack([left1, tf.image.flip_left_right(left1)])
    ll=sess.run(leftp)`

And finally I used `feed_dict` to replace the placeholder left with an actual image as 4D tensor
`disp = sess.run(model.disp_left_est[0], feed_dict={left:ll})`

The code actually runs successfully but doesn't generate a valid disparity map. The output is more like edge detection. Can you please tell what am I missing?
Thank you.

**Comment by aqeelanwar** [comment]
Never mind, I figured out the issue. The model accepts normalized test image where the pixel range is 0 to 1. Dividing the read image by 255 solved the issue.

**Comment by wolhandlerdeb** [comment]
Hi,
can yo send me your changes to be able to accept a video as input
Thanks
