### ISSUE TITLE
RandomShuffleQueue running out of elements.

### ISSUE THREAD

**Issue by slippy0** [mrharicot/monodepth#28]
When attempting to train, the queue behind the shuffle batch keeps running out before even one epoch. The exact iteration isn't deterministic, but is usually around iteration 150. 

The exact command I'm using is as follows:

`python monodepth_main.py --mode train --model_name my_model --data_path <path to my data> --filenames_file utils/filenames/kitti_train_files.txt --log_directory logs --num_gpus=4`

I've attempted to greatly increase min_after_dequeue in monodepth_dataloader by about a factor of 10 (which has helped me with this problem in the past), but it had no effect. In fact, greatly _reducing_ it also had no effect on when the queue emptied. I haven't made any changes to the code, so I'm not sure what could be causing issues.

I'm using TF 1.1.0, CUDA 8.0.61, and python 2.7.12 on ubuntu

And thanks for sharing your code!

**Comment by mrharicot** [comment]
Hi,

You are likely pointing to the wrong directory with your --data_path.
Are you sure the files are located there?
The code essentially appends the filenames in the --filenames_file to the --data_path.

**Comment by slippy0** [comment]
I downloaded all the files from kitti_archives_to_download to a folder, then unzipped all of them to the same folder. 
I don't get any "file not found" warnings, which I _DO_ get if I point to an entirely different folder. Also, it does successfully run for around 150 iterations, so some amount of data is being read correctly.

Here is an excerpt of the log (being run on one GPU):

    batch     10 | examples/s: 5.44 | loss: 1.62449 | time elapsed: 0.01h | time left: 194.87h
    batch     20 | examples/s: 5.48 | loss: 1.61212 | time elapsed: 0.02h | time left: 136.22h
    batch     30 | examples/s: 5.48 | loss: 1.52496 | time elapsed: 0.02h | time left: 116.12h
    batch     40 | examples/s: 5.48 | loss: 1.65349 | time elapsed: 0.02h | time left: 106.07h
    batch     50 | examples/s: 5.47 | loss: 1.45446 | time elapsed: 0.03h | time left: 100.10h
    batch     60 | examples/s: 5.46 | loss: 1.23633 | time elapsed: 0.03h | time left: 96.13h
    batch     70 | examples/s: 5.47 | loss: 1.27417 | time elapsed: 0.04h | time left: 93.26h
    batch     80 | examples/s: 5.47 | loss: 1.32178 | time elapsed: 0.04h | time left: 91.12h
    batch     90 | examples/s: 5.46 | loss: 1.52829 | time elapsed: 0.04h | time left: 89.49h
    batch    100 | examples/s: 5.41 | loss: 1.10352 | time elapsed: 0.05h | time left: 88.18h
    batch    110 | examples/s: 5.44 | loss: 1.06918 | time elapsed: 0.05h | time left: 87.11h
    batch    120 | examples/s: 5.42 | loss: 1.10744 | time elapsed: 0.06h | time left: 86.23h
    batch    130 | examples/s: 5.45 | loss: 1.21978 | time elapsed: 0.06h | time left: 85.46h
    batch    140 | examples/s: 5.44 | loss: 1.17131 | time elapsed: 0.07h | time left: 84.82h
    batch    150 | examples/s: 5.44 | loss: 1.04223 | time elapsed: 0.07h | time left: 84.26h
    batch    160 | examples/s: 5.44 | loss: 1.17867 | time elapsed: 0.07h | time left: 83.77h
    2017-08-01 21:57:39.452514: W tensorflow/core/framework/op_kernel.cc:1152] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 4)
    	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

**Comment by mrharicot** [comment]
Hum, that's weird.
Are you running on a CPU or a slow GPU?
The number of examples/s is very low, I wonder if it has anything to do with that.
Do you run out of memory maybe?

**Comment by slippy0** [comment]
The data is on a HDD, not SSD, for now. 
I have 64GB of RAM, and usage hovers around 4GB, so that isn't the cause. 
The GPUs are K80s with 12GB memory. If they were running out of memory, I'm pretty sure TF would be throwing an error instead of the queue running out.

**Comment by mrharicot** [comment]
I'm running out of ideas here.
The only thing I can think of is the speed of the HDD.
Did you convert the images to jpeg?

**Comment by slippy0** [comment]
I did. 
It seems like I'm the only one having this problem, so I'll do some more in-depth debugging on my end.

**Comment by mrharicot** [comment]
You should be able to plot the queue capacity in tensorboard, which might help debugging

**Comment by Tenacity-soar** [comment]
When i test the model_kitti ,a problem occured, 
Traceback (most recent call last):
  File "monodepth_simple.py", line 120, in <module>
    tf.app.run()
  File "/home/akasha/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 117, in main
    test_simple(params)
  File "monodepth_simple.py", line 67, in test_simple
    input_image = scipy.misc.imresize(input_image, [args.input_height, args.input_width], interp='lanczos')
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 487, in imresize
    imnew = im.resize(size, resample=func[interp])
KeyError: 'lanczos'
I need help

**Comment by slippy0** [comment]
@Tenacity-soar - this is entirely unrelated to my issue, so in the future please open your own issue...

You likely have an outdated version of scipy. Lanczos resizing was [added in version 0.18.0](https://github.com/scipy/scipy/pull/6022).

**Comment by Tenacity-soar** [comment]
Thank you very much. I will follow your guide.

**Comment by yzcjtr** [comment]
I've come across exactly the same problem. Have you got any solutions? @slippy0

**Comment by slippy0** [comment]
Not yet. Sadly my project path took me in a different direction, so I haven't had time to revisit this. 

I got as far as setting up a summary on queue usage, but I actually was having some difficulty - I'm not sure which variable to be charting.

**Comment by Tenacity-soar** [comment]
Thanks for your help. I have run the program successfully! I have read the code five days.
But I don't understand the
_, loss_value = sess.run([apply_gradient_op, total_loss])
what is the meaning of the loss_value?
Thanks

**Comment by yzcjtr** [comment]
@slippy0 I guess you didn't convert the png images to jpeg, nor did I. I rewrote my dataloader and the problem still persisted. While after I convert them to jpeg, everything goes well now. It's quite strange but my problem gets solved now.

**Comment by swehrwein** [comment]
I'm having the same problem, queue is empty usually around iteration 270. Increasing number of threads and disabling augmentation has no effect, so it's probably not cpu-limited. Data is loaded from jpg images on a HDD - I don't have an SSD available.

@yzcjtr can you give any more detail about how you changed the dataloader?

A hint for how to log the queue size to tensorboard would also be helpful if anyone has tips.

**Comment by slippy0** [comment]
@yzcjtr I haven't tried to fix it yet, but I bet that was the problem. I did some quick grepping and found that while most of my images were pngs, about 1000 were jpgs. I think I started then killed a script to convert to jpg, but then didn't clean up. 

I'm going to mark this as closed, as I have enough reason to believe the problem lies on my end.

**Comment by swehrwein** [comment]
/sigh I found the problem on my end - a few of the jpegs were corrupted. Exceptions that occur in tf's queue threads produce no output, so you don't get any stack trace or anything to help you out.

In case it helps anyone else, I tracked down the bad files with
`cat utils/filenames/kitti_train_files.txt | sed 's/ /\n/' | parallel jpeginfo -q -c $KITTI/{} | grep -v OK`

**Comment by mrharicot** [comment]
Glad you both figured it out!
