### ISSUE TITLE
how to get the depth values from the disparity images? what are the values of b and f for KITII dataset?

### ISSUE THREAD

**Issue by liyancas** [mrharicot/monodepth#31]

**Comment by MeghaMaheshwari** [comment]
I think this part of the code is available in evaluate_kitty.py where the depth is calculated from the disparity

**Comment by callme739** [comment]
Hi,

How did you get to know the Cityscapes baseline(0.22m) and focal(2262)?
As for baseline, it is described in the original paper of Cityscapes, but I can not find about focal.
