### ISSUE TITLE
Depth estimation on custom images

### ISSUE THREAD

**Issue by MeghaMaheshwari** [mrharicot/monodepth#33]
I trained the network on the kitti dataset and wanted to get the depth of some custom images as my test set. I have only one set of images (not stereo) but the depth I am getting doesnt look very good. Any suggestions on what can I do. Please see the images that I saved from the generated disparity map on the custom images.

![1](https://user-images.githubusercontent.com/8704236/29147349-42f0ff8c-7d1b-11e7-9eed-c5f177f30c91.png)
![4](https://user-images.githubusercontent.com/8704236/29147352-4683f758-7d1b-11e7-89d9-1b3eacf06cfc.png)
![2](https://user-images.githubusercontent.com/8704236/29147353-48ff7444-7d1b-11e7-8138-6dffcfe4b7ac.png)

**Comment by mrharicot** [comment]
Hi,
Do you also have the corresponding input images?
It looks like there is a lot of distortion in these images.
Any data that looks too different from the training one will produce unreliable results, and given that we trained on at most 2 datasets it is fairly easy to find images that have different statistics.

**Comment by MeghaMaheshwari** [comment]
Let me send you the input images in sometime? Do you suggest that I should re-train the network with the new set of images. Is there any other suggestion in case the input images have different statistics compared to what you have trained on?

**Comment by MeghaMaheshwari** [comment]
Hey could you give me your email address? I would like to send u the images so that I can know what exactly the issue is.

**Comment by mrharicot** [comment]
Hi, you can find it on my personal page.
http://www0.cs.ucl.ac.uk/staff/C.Godard/

**Comment by MeghaMaheshwari** [comment]
Hi...I have sent you the images.

**Comment by MeghaMaheshwari** [comment]
Hi..I sent the images to c.godard@cs.ucl.ac.uk but the mail bounced back. Could you please help me verify if its the correct mail address?

**Comment by mrharicot** [comment]
Hi, 
I did not receive it, but the email was correct (I redacted it to avoid spamming).
Can you try my gmail address? it's mr.haricot

**Comment by Gatsby23** [comment]
@MeghaMaheshwari Hey, can you help me how to develop the depth image ? I have use the focal and baseline to convert the disparities to the depth, but when I save it as a **.png. The value has been converted to the RGB color form and can't get the depth value through imread(**.png) in Matlab. So can you help me with that?
