### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jeongc** [mrharicot/monodepth#37]
Hi 

Thanks for your wonderful works!
After reading your papers, I have a few questions. It would be great helpful if you share some informations.

1. Scale issue. Your paper did not mention anything about the well-known scale issue of monocular depth method. Do you think your algorithm/network overcomes the scale issue? 

2. Gray vs. color images. Did you ever try with gray images with the same conditions? If you did, could you share any comparison or opinion?

3. KITTI full-resolution. It seems that your result of stereo is good. Did you evaluate on the official KITTI evaluation server with full-resolution images or do you have plan to do?

Regards,
CJ

**Comment by mrharicot** [comment]
Hi,

1.  Yes and No. It is obviously able to figure out the scale of the scene as it produces fairly accurate depths. But it was also trained on a very similar scenes, the scale ambiguity isn't really there.

2. We only used color images for training, however we randomly scales the rgb values at training time to make it less color dependent. I did not try on bw images at test time.

3. No, the stereo was just a quick experiment to show that our model was able to learn different tasks given the same architecture.

I hope this helps!

Best,
Clément

**Comment by xjoshramos** [comment]
gray image inference on pre-trained color kitti vgg.

![0000000000](https://user-images.githubusercontent.com/4721207/29642359-366616aa-881d-11e7-9240-990db604bbc8.jpg)

![0000000000_disp](https://user-images.githubusercontent.com/4721207/29642365-3a001cc0-881d-11e7-9da5-e4a5a3ce68b5.png)

**Comment by mrharicot** [comment]
Hi,

I think something else went wrong here, the output looks like it concatenated two depthmaps next to each other.
What did you run exactly?

**Comment by xjoshramos** [comment]
mono_simple.py on pretrained kitti_model set.

**Comment by mrharicot** [comment]
I just fixed it.
![kitti_bw_disp](https://user-images.githubusercontent.com/5363877/29992269-7bc8a66e-8f4c-11e7-972e-59f326c7dec1.png)

**Comment by xiaohedu** [comment]
Hi @mrharicot @xjoshramos 
if I train monodepth with gray images, could you provide me some advice about code modification?,thank you!
