### ISSUE TITLE
InvalidArgumentError (see above for traceback): Incompatible shapes: [8,94,310,1] vs. [8,94,309,1]

### ISSUE THREAD

**Issue by JoestarK** [mrharicot/monodepth#4]
Hi, mrharicot 
Thanks for your work! 
I got the follow error while training model using original size of kitti:
`InvalidArgumentError (see above for traceback): Incompatible shapes: [8,94,310,1] vs. [8,94,309,1]`

Training code:
`python monodepth_main.py --mode train --model_name kitti_model --data_path /mnt/nfs/ybwang/data/monodepth/ \
--filenames_file ./utils/filenames/kitti_train_files.txt --input_height 376 --input_width 1241 --log_directory ./logs/`

**Comment by mrharicot** [comment]
Hi JoestarK,

The fully convolutional models used only take inputs that are mulitples of **128** for [vgg](https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L185) or **64** for [resnet50](https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L245).

The original ratio of KITTI (3.3) makes it annoying to use, 3 or 3.5 ratios might be easier to get.
You can use a 3x10 ratio giving 192x640 for Resnet50 (3.33)
If you want to use almost full size images you can use 6x20 to get 384x1280.

The pretrained models were trained with 256x512, if you feed something quite different, it will very likely output weird stuff.
