### ISSUE TITLE
Error for testing stereo trained model

### ISSUE THREAD

**Issue by xjoshramos** [mrharicot/monodepth#40]
Assign requires shapes of both tensors to match. lhs shape= [7,7,3,32] rhs shape= [7,7,6,32]

Does this mean the input to a stereo model is left right concatenated?

**Comment by xjoshramos** [comment]
Parameters for the model trained.

parameters(encoder='vgg', height=256, width=512, batch_size=8, num_threads=8, num_epochs=50, do_stereo=True, wrap_mode='border', use_deconv=True, alpha_image_loss=0.85, disp_gradient_loss_weight=0.1, lr_loss_weight=1.0, full_summary=False)
total number of samples: 15875
total number of steps: 99250

**Comment by xjoshramos** [comment]
Do I need to toggle --do_stereo in mono_simple.py even though inference does not require stereo images on a model trained with --do_stereo?

**Comment by mrharicot** [comment]
Yes, the stereo model expects two concatenated images
https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L295

**Comment by xjoshramos** [comment]
How would the input work in mono_simple.py ?

**Comment by mrharicot** [comment]
You will need to change [line 52](https://github.com/mrharicot/monodepth/blob/master/monodepth_simple.py#L52) to have 6 channels instead of 3.
And you will need to change [line 109](https://github.com/mrharicot/monodepth/blob/master/monodepth_simple.py#L109) to True.

**Comment by caltech91** [comment]
Hi!
I changed line52 and line109 and gave the input image to /home/mk/anaconda3/envs/tensor/monodepth-master/wean/images/*.jpg.
However, an error occurred.

TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [float32, <NOT CONVERTIBLE TO TENSOR>] that don't all match.

**Comment by petitchamp** [comment]
> You will need to change [line 52](https://github.com/mrharicot/monodepth/blob/master/monodepth_simple.py#L52) to have 6 channels instead of 3.
> And you will need to change [line 109](https://github.com/mrharicot/monodepth/blob/master/monodepth_simple.py#L109) to True.

I think you mean line 99 to be True
