### ISSUE TITLE
monodepth standard deviation code of the disparities per pixel?

### ISSUE THREAD

**Issue by JackHenry1992** [mrharicot/monodepth#41]
As you said, the network gets confused with texture-less regions, I want to use standard deviation filter to 
 delete this area.
![image](https://user-images.githubusercontent.com/9390228/29768690-de2b85d2-8c19-11e7-9e71-b1a695d6c69b.png)

**Can you give your standard deviation code or calculate-method?**

Thanks very much for sharing this prefect job.

**Comment by mrharicot** [comment]
Hi,

To get standard deviation I ran the training data augmentation on the same frame a few times (20? I can't remember) and computed the standard deviation per pixel.
