### ISSUE TITLE
Error when trying to run on an image

### ISSUE THREAD

**Issue by Tetsujinfr** [mrharicot/monodepth#42]
hi,

when doing the simple call to run the algo on my image with the below command found on the readme:
`python monodepth_simple.py --image_path ~/monodepth/img/20170828_121009.jpg --checkpoint_path ~/monodepth/models/model_eigen`

I got a set of errors starting with:
`W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/tets/monodepth/models/model_eigen: Failed precondition: /home/tets/monodepth/models/model_eigen: perhaps your file is in a different file format and you need to use a different restore operator?`

I suspect it relates to the way I named the models but not sure.
under ~/monodepth/model/model_eigen/ I just have the two 365Mb files disparities.npy and disparities_pp.npy I extracted from your model page.

I have Tensorfow 1.2.1 installed and Cuda 8.0, running a GTX980Ti.

Not sure what I am doing wrong. Also I do not see any checkpoint files in the folders, should I have some?

Can you help please?
thank you

Tets

**Comment by mrharicot** [comment]
Hi,

You downloaded the results instead of the models.
Please use the script [here](https://github.com/mrharicot/monodepth#models) to download the correct model.

**Comment by Tetsujinfr** [comment]
Merci beaucoup. Indeed, I moved too quickly on this one. With the right files all processes like a charm.
Now I have so not o great results, is it because given the training dataset, any inference on something else than streets with cars will not work very well?
I attach an exemples:
/home/tets/monodepth/img/test.jpg
/home/tets/monodepth/img/test_disp_city2kitti.png

/home/tets/monodepth/img/out-00710.jpg
/home/tets/monodepth/img/out-00710_disp_city2kitti.png

**Comment by duylp** [comment]
Hi, I also met the same problem when testing on an image. Inside the model, there are 3 files `model_kitti.data-00000-of-00001`, `model_kitti.index` and `model_kitti.meta` but it could not load checkpoint.

**Comment by mrharicot** [comment]
@Tetsujinfr Don't expect it to produce any reasonable results on scenes where the ground isn't visible. This model was trained on street scenes, the further away you get from this the less likely it will be for the network to produce something correct.

@duylp you need to point the checkpoint path to the folder which has these 3 files and put the base name of these 3 files:
`--checkpoint_path ~/my/folder/model_kitti`
**Also please search for your issue first, this has been solved multiple times, and create a separate thread instead of using one which is unrelated.**

**Comment by Tetsujinfr** [comment]
Ok thanks a lot for your clarifications. indeed the results are spectacular provided the photo contains the right context.
![tufnell2](https://user-images.githubusercontent.com/29961693/29938047-56d0709e-8e7f-11e7-8a70-279ea37054a9.jpg)
![tufnell2_disp](https://user-images.githubusercontent.com/29961693/29938050-593dea28-8e7f-11e7-8f26-0046533b421f.png)

I am closig the issue.

All the best in Seattle and thanks for sharing your great work and ideas and help, much appreciated.
Maybe  will produce a video out of your code on my channel https://www.youtube.com/user/Tetsujinfr
a+ et vive la France
Tets
