### ISSUE TITLE
Question about performance on small scene

### ISSUE THREAD

**Issue by jhneo** [mrharicot/monodepth#47]
Hi
Your works is wonderful!
I have a few questions.I wonder  if you could share some informations.
Since your method produces state of the art results on the KITTI dataset,which is a outside scene,a big scene.I am curious about the performance of your model on small scene dataset (such as small toys and multi-view stereo performs well). Do you think your method can achieve good accuracy in small scene dataset after trained on the dataset?

Regards,
JH

**Comment by mrharicot** [comment]
Hi,

The network was trained on street scenes to it will expect similar scenes at test time.
It is very unlikely that this model will produce anything reasonable for a scene made with small toys.
If the scene resembles a street scenes (let's say mad out of legos) it might produce a reasonable result, but the scale will be wrong.

If you retrain the model on similar scene then it should perform reasonably well.

**Comment by jhneo** [comment]
Thank you for your reply.
