### ISSUE TITLE
File not in the repo

### ISSUE THREAD

**Issue by parhartanvir** [mrharicot/monodepth#5]
Hello,
I cannot see the file **kitti_files_to_download.txt** in the repo.
Thanks

**Comment by mylxiaoyi** [comment]
I think it would be [this](https://github.com/mrharicot/monodepth/blob/master/utils/kitti_archives_to_download.txt)

**Comment by mrharicot** [comment]
Hi,

There was a typo in the filename, the actual file is called kitti_archives_to_download and is located under utils/
