### ISSUE TITLE
rightImg8bit_trainvaltest 

### ISSUE THREAD

**Issue by scholltan** [mrharicot/monodepth#53]
hi，I  register in  the Cityscapes but only the leftImg can be downloaded,  could you tell me how to download the rightimgs ?

**Comment by RichardChe** [comment]
Hi, have you downloaded the right image dataset yet? How？

**Comment by mrharicot** [comment]
Hi,
You have to request it by emailing the cityscapes team, the email address is somewhere on the webpage.

**Comment by RichardChe** [comment]
Thanks.
