### ISSUE TITLE
fine-tuning on pre-trained models 

### ISSUE THREAD

**Issue by AhmedShaban94** [mrharicot/monodepth#57]
we tried to fine tune pre-trained models with KITTI dataset or other dataset but it keeps outputting the following error : Assign requires shapes of both tensors to match. lhs shape= [7,7,6,64] rhs shape= [7,7,3,64] 
knowing that the code works well when we train on any dataset from scratch !

**Comment by mrharicot** [comment]
Hi,
What image sizes are you using?
Can you show me the exact lines you executed as well as the error message?

**Comment by mrharicot** [comment]
With the current architecture, because of the depth and the strided convolutions you need to use input sizes of multiples of 128 for vgg or 64 for resnet50.

**Comment by AhmedShaban94** [comment]
we've already used input sizes of 512x256 and they're multiples of 64 (knowing that we're using resnet50). 
but yet we got the same exact error, Can you provide further explanation ?

**Comment by mrharicot** [comment]
oh, I see.
You are trying to load a monocular pretrained model while training a stereo model, this won't work.
I will make the stereo pretrained model available when I have time.

**Comment by AhmedShaban94** [comment]
Ok, Thank you ! :+1:
