### ISSUE TITLE
Network Output

### ISSUE THREAD

**Issue by titoghose** [mrharicot/monodepth#6]
Hi Clement,
I want to use your model for a project i am currently working. I had two questions regarding the same. 
Firstly, till what distance does it accurately predict? 
Secondly, can we extract the real distance in meters from the depth map?

**Comment by mrharicot** [comment]
Hi,
The model's accuracy gets worse as the point is further, object boundaries are also not always very reliable.
Yes you can convert disparities to depth, have a look at [evaluation_utils.py](https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L43).
Please note this piece of code only works on models trained on kitti, for the cityscapes model the baseline and focal length are different.
