### ISSUE TITLE
How can I get the predict distance for my testing images 

### ISSUE THREAD

**Issue by LaiAmy** [mrharicot/monodepth#63]
Hi , 
I have the focal ,baseline with my camera (stereo) for training.
How can I get the predict distance for my testing images (monocular) ?
I don't have the ground truth for testing images .

**Comment by mrharicot** [comment]
Hi,
You can convert disparity to depth using the following formula:
depth = focal * baseline / disparity
The focal has to be in pixels and the baseline in meters.
This formula is only valid if your stereo pair has been calibrated such that points at infinity have no disparity.

**Comment by psnow** [comment]
Hi LaiAmy and mrharicot,
    I am a beginner, would you like to use which script to train your own stereoscopic image pair, or whether can fine-tuning an existing model. How to do it ?

    In addition, I also played Deep3d-TF(https://github.com/JustinTTL/Deep3D_TF), but there seems to be no good results.

**Comment by LaiAmy** [comment]
Hi , mrharicot ~
Thank you for you reply  . 
And I saw the disparity are divided into 0 ~ 255 .
I test different images and each has different distance .
but the disparity still be divided from 0 to 255.
Does any standard between the value ( 0~255 ) ?

I use the focal & baseline to calculate the distance , and if disparity are  0 ~ 255 .
I can get  0 ~ 8.9 meters . 
Is it correct ?

**Comment by mrharicot** [comment]
@psnow please see the main readme, everything is explained there
@LaiAmy are you using the output image or the numpy array?
The disparities are float32 and should be in a file ending in `_disp.npy` the outputted image is just for visualization.

**Comment by LaiAmy** [comment]
Hi , psnow
I use my stereo camera to collect data .
If you want to using an existing model , you can download it from this github .

**Comment by LaiAmy** [comment]
I using the numpy array to calculate.
  
original_height, original_width, num_channels = input_image.shape
input_image = scipy.misc.imresize(input_image, [args.input_height, args.input_width], interp='bicubic')
input_image = input_image.astype(np.float32) / 255
input_images = np.stack((input_image, np.fliplr(input_image)), 0)
disp = sess.run(model.disp_left_est[0], feed_dict={left: input_images})
disp_pp = post_process_disparity(disp.squeeze()).astype(np.float64)
disp_to_img = scipy.misc.imresize(disp_pp.squeeze(), [original_height, original_width])

I use the disp_to_img to calculate the distance.
Is it OK ?

**Comment by mrharicot** [comment]
Yes disp_to_img should be correct.
However I do not understand what you meant by:
> And I saw the disparity are divided into 0 ~ 255 .

**Comment by LaiAmy** [comment]
Oh , it's my wrong .
You solved my problem .
Thank you so much .
