### ISSUE TITLE
Unable to download pre-trained weights

### ISSUE THREAD

**Issue by villanuevab** [mrharicot/monodepth#64]
Hello, I would love to test this model on my own setup. However, the connection to http://visual.cs.ucl.ac.uk/pubs/monoDepth/models/ times out whenever I attempt to download the pre-trained weights. Is there anywhere else I can download the pre-trained weights from? 

```
--2017-10-26 17:12:50--  (try: 3)  http://visual.cs.ucl.ac.uk/pubs/monoDepth/models/model_kitti.zip
Connecting to visual.cs.ucl.ac.uk (visual.cs.ucl.ac.uk)|128.16.10.31|:80... failed: Connection timed out.
Resolving visual.cs.ucl.ac.uk (visual.cs.ucl.ac.uk)... 128.16.10.31
Connecting to visual.cs.ucl.ac.uk (visual.cs.ucl.ac.uk)|128.16.10.31|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

**Comment by mrharicot** [comment]
Hi,
I think the website went down during the night.
It seems to be fine now, can you confirm?

**Comment by mrharicot** [comment]
Closing as the website seems to be fine now.

**Comment by villanuevab** [comment]
Yes, thank you for your quick response. I just finished downloading the weights.

**Comment by FancyXun** [comment]
I attempt to download the pre-trained weights but failed. Is there anywhere else I can download the pre-trained weights from?
`Connecting to visual.cs.ucl.ac.uk|128.16.10.31|:80... failed: Connection refused.`

**Comment by mrharicot** [comment]
Hi,
The ucl website seems to be down, it should be back up in a few hours.
