### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by kschan** [mrharicot/monodepth#66]
I've been doing some work with your models and have noticed that they are training rather slowly. I'm getting about 20 examples/second and I'm using a NVIDIA P40. I used the timeline profiler to see what was going on and noticed a few ops especially in the bilinear sampler that were taking much longer than others.  Here's the profiler output JSON file which is viewable with chrome://tracing

https://www.dropbox.com/s/mz0hhpswpg163uz/timeline_01.json?dl=0

Not sure if you've used this profiler before or if these are expected. I'm relatively new to TF in general so don't know if this is typical. Let me know what you think!

**Comment by mrharicot** [comment]
Hi,
Thanks for profiling!
The bilinear sampler implementation is indeed really inefficient.
I modified an implementation of the Spatial Transformer from TF 0.10 at the time.

The best way to improve on this would be to use the cuDNN API which would significantly accelerate this operation.
http://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnSpatialTfSamplerForward
