### ISSUE TITLE
trying to run test getting error 

### ISSUE THREAD

**Issue by rnunziata** [mrharicot/monodepth#7]
python monodepth_main.py --mode test --data_path data/kitti --filenames_file utils/filenames/kitti_test_files.txt --log_directory tmp/ --checkpoint_path tmp/my_model/model-181250.
All files references resolve correctly also tried this with stereo filenames , same error.

```
Traceback (most recent call last):
  File "monodepth_main.py", line 254, in <module>
    tf.app.run()
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 251, in main
    test(params)
  File "monodepth_main.py", line 187, in test
    model = MonodepthModel(params, args.mode, left, right)
  File "/home/richard/opencv3-p3-code/monodepth/monodepth_model.py", line 49, in __init__
    self.build_model()
  File "/home/richard/opencv3-p3-code/monodepth/monodepth_model.py", line 291, in build_model
    self.left_pyramid  = self.scale_pyramid(self.left,  4)
  File "/home/richard/opencv3-p3-code/monodepth/monodepth_model.py", line 81, in scale_pyramid
    scaled_imgs.append(tf.image.resize_area(img, [nh, nw]))
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 757, in resize_area
    align_corners=align_corners, name=name)
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 499, in apply_op
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'size' of op 'ResizeArea', got [<tf.Tensor 'model/truediv:0' shape=() dtype=float64>, <tf.Tensor 'model/truediv_1:0' shape=() dtype=float64>] of type 'list' instead
```

**Comment by uyekt** [comment]
same here

**Comment by mrharicot** [comment]
Hi,

What version of Tensorflow are you using?
The code was written for TF 1.0, I haven't tested/ported it to TF 1.1 yet.

**Comment by rnunziata** [comment]
```
python3 -c 'import tensorflow as tf; print(tf.__version__)' 
1.2.0-rc0
```

**Comment by mrharicot** [comment]
The code was written for python 2, could you try running it with it?

**Comment by rnunziata** [comment]
yes...much better. Past beyond this error.

However I am having issue. I am not sure what to pass to call.

I downloaded images from 2011_09_26_drive_0048_extract.zip
I downloaded disparities_kitti.zip. kitti_data_scene_flow.zip and  contents are as follows:

kitti data directory
- disparities.npy  
- disparities_pp.npy  
- model_kitti.data-00000-of-00001  
- model_kitti.index  
- model_kitti.meta  
- testing 
- training

`python monodepth_main.py --mode test --data_path ../data/monodepth/2011_09_26/2011_09_26_drive_0048_extract/image_00/data/???   --filenames_file utils/filenames/kitti_test_files.txt --log_directory tmp/ --checkpoint_path ../data/monodepth/kitti/model???
`
I put question marks above as I am not sure what to put here.
error:

```
 NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./../data/monodepth/kitti/
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
```

The kitti_test_files.txt references 2011_10_03/2011_10_03_drive_0047_sync/

Thank you for your help.

**Comment by yeyang1021** [comment]
@rnunziata   --checkpoint_path ./../data/monodepth/kitti/    the path is error. 
The path may be:    ./../data/monodepth/kitti/model_kitti

**Comment by mrharicot** [comment]
@yeyang1021 is right, the `checkpoint_path` should match the filename of the checkpoint without the extensions so for example:
`../data/monodepth/kitti/model_kitti` or `../data/monodepth/kitti/model_city2kitti`

**Comment by rnunziata** [comment]
Thank you...moving to python 2.7 and fixing the reference worked ....
