### ISSUE TITLE
Error in `python`: free(): invalid pointer

### ISSUE THREAD

**Issue by satyarth934** [mrharicot/monodepth#74]
Ubuntu - 14.04
Tensorflow - v1.0.0
Python - 2.7.6 

I am facing this issue while training on my data.
https://github.com/tensorflow/tensorflow/issues/9328

**Comment by mrharicot** [comment]
Hi,
Do you mind sharing a bit more information so I can try to help?

What command did you use? 
What kind of data are you training on?
Can you share the entire error message?
Does it work if you train using KITTI or cityscapes?
Is testing working fine?
