### ISSUE TITLE
'do_project' is always false

### ISSUE THREAD

**Issue by ganyk** [mrharicot/monodepth#77]
hi, i find out that the `do_project` variable in monodepth_model.py is always false, since `tf.shape(x)[3]` is a tensor and `num_layers` is a digit, they will not be equal under any circumstances.
`do_proj = tf.shape(x)[3] != num_layers or stride == 2`

Thus there is a shortcut in each resconv block, and the network structure built by this code is not the 'standard' resnet.

**Comment by mrharicot** [comment]
Hi,
Thanks for pointing it out. I am already aware of this, I haven't fixed it yet in order to stay consistent with the published method.
I do however plan on cleaning up the code to make a separate version at some point.
