### ISSUE TITLE
 The same depth of image to training 

### ISSUE THREAD

**Issue by LaiAmy** [mrharicot/monodepth#78]
I use my stereo camera to collect data.
I collect four different distances : 0.5m , 1m , 1.5m , 2m
Like the following :
![zed_image902](https://user-images.githubusercontent.com/29377877/33269316-3321bf1e-d3bb-11e7-9682-a86fcdb83607.jpg)
![zed_image1208](https://user-images.githubusercontent.com/29377877/33269337-48c87614-d3bb-11e7-889a-1933432754d9.jpg)
![zed_image1702](https://user-images.githubusercontent.com/29377877/33269385-6ecc9c64-d3bb-11e7-8b28-dffd6434ecc7.jpg)
![zed_image2203](https://user-images.githubusercontent.com/29377877/33269359-5ae08490-d3bb-11e7-9877-14c5b62e7460.jpg)

The picture are painted walls.
Make the whole picture is the same depth.

My image's resolution is 1280*720.
All training data are 2224 images.
But the result are very bad.
Does any one know what's wrong with this ?

Are my images of  training data too less ?
Or , the whole picture is the same depth affect the network to learning ?
Or , other reasons affect the result is not good ?

Thank you .

**Comment by mrharicot** [comment]
Hi,
Can you share some examples of what the network produces?
Do you want to train a monocular system, or a stereo one?
The data is very difficult for a monocular system, there is very little information available for the network to figure out how far away the scene is.
In the worst case, the network might just learn to recognize the four different cases (distances) and guess from these.

**Comment by LaiAmy** [comment]
I want to train a monocular system.
And before training ,  I guess it can recognize the four different cases .
But the results like following : 
Input (the same depth)
![501](https://user-images.githubusercontent.com/29377877/33303533-a168e988-d43e-11e7-8a45-d6375e670741.jpg)
Output(it seems can't know any disparity)
![50](https://user-images.githubusercontent.com/29377877/33303526-9393a87a-d43e-11e7-9fc0-db7188caf949.JPG)

I test any training image , the result all like above .

**Comment by mrharicot** [comment]
Hi,
I think the data you are trying to learn from is just too difficult.
There are very little clues to help the network figure out from a single image how far away the scene is.
One good rule of thumb is: if you can't guess it yourself, then the network will have a really hard time doing so.

**Comment by LaiAmy** [comment]
Hi , 
Thank you for your reply .
I just want to try this data for training . 
Now , I use  more difference depth clue images to train the network.
I expect it will have a good result.
