### ISSUE TITLE
 Try it on one image，meet InvalidArgumentError problem

### ISSUE THREAD

**Issue by LeisureLiu** [mrharicot/monodepth#79]
Hi，
I just want to  try on one image, and I use your  pre-trained models `model_kitti_resnet`, the test image is come from kitti. I got the error: 

>  InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64] rhs shape= [32]

What should I do to solve it?

**Comment by mrharicot** [comment]
Hi,

You need to use the flag `--encoder resnet50` when using the resnet model
