### ISSUE TITLE
How to generate ground truth visualization like in Figure 4

### ISSUE THREAD

**Issue by thuyang** [mrharicot/monodepth#8]
Hi all,
I am wondering how to generate the dense visualization of ground truth as in Figure 4? The results from the lidar is a set of sparse cloud points. Should I use some kind of filter to generate the dense depth map?

Thank you!

**Comment by mrharicot** [comment]
Hi,

We used a similar function to [this one](https://github.com/hunse/kitti/blob/master/kitti/velodyne.py#L40).
We only used this interpolation for visualization purposes.
