### ISSUE TITLE
Converting disparity to depth map

### ISSUE THREAD

**Issue by madhubabuv** [mrharicot/monodepth#80]
Hi,

Firstly, thanks for sharing your code with us. I am using your code in my project. As per the paper, the output of disparity was constrained in between **0, 0.3* width** of the image at the given scale. But in evalution_utils.py, you have multiplied that with width only. Would be there no problem with that?

Another thing, in the paper you mentioned **scaled sigmoid non-linearity**, what does it mean exactly?

**Comment by mrharicot** [comment]
Hi,
The code in evaluation_utils is only used for evaluation.
We constrain the disparity to be at maximum 30% of the width in the `get_disp` function:
https://github.com/mrharicot/monodepth/blob/master/monodepth_model.py#L124
