### ISSUE TITLE
GT interpolation

### ISSUE THREAD

**Issue by jpyusiong** [mrharicot/monodepth#86]
Hi,

I would like to ask about Figure 4, specifically on the ground truth depth interpolation for visualization purposes. I assume this is not part of the code you have provided here, right? Would like mind providing me with how is this done? Thank you.

**Comment by mrharicot** [comment]
Hi,
[It is](https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L216)!

**Comment by jpyusiong** [comment]
Oh, I see. Thanks. I thought those were not the lines of code for GT interpolation because the objects in the generated image are not complete. But when I checked the soft copy of your paper again and zoomed in the GT images in Figure 4, I got the same GT images.
