### ISSUE TITLE
The evaluation result is poor and the program crashes everytime I perform.

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#91]
Hi 
Just try to evaluate my outcome by "evaluate_kitty.py"...but the result is poor. 
data_scene_flow/training/image_2/000005_10.png
![000005_10](https://user-images.githubusercontent.com/8175070/34429043-c618c674-ec8d-11e7-920f-55b13b74e24d.png)
![000005_10_disp](https://user-images.githubusercontent.com/8175070/34429046-c9ae6b5e-ec8d-11e7-9074-7205c5fe5433.png)

 abs_rel,    sq_rel,      rms,    log_rms,     d1_all,         a1,         a2,         a3
0.6410,   10.8658,    12.912,    0.592,     91.047,      0.168,      0.549,      0.770

Are you having chance to get the poor result just like mine?

By the way, how long does it takes to run the monodepth_simple.py? For me, there are several situation.....
sometimes it takes 0.3 sec
sometimes it takes 3 sec
sometimes it takes 7 sec 
sometimes it takes over than 7sec
**Actually, most of time it crushes and leads to my computer frozen. and I wonder that do you have this kind of situation?**

Anyhow, today I got the result for about 5 to 6 sec...
 I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
 I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
 I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.329
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.63GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2)
depth calculating operation time: 5.629680 sec

**Comment by mrharicot** [comment]
Hi,

Visually it looks fine to me.
What model did you use or train and what split did you choose to test on?

monodepth_simple should be relatively fast, maybe a couple of seconds, it does have to build a new graph every time so it its quite inefficient.
However I never had any instability with it.
When googling your error message, it seems that you might have a gpu driver issue:
https://github.com/tensorflow/tensorflow/issues/8352

**Comment by keishatsai** [comment]
Hi @mrharicot ,
Thanks for replying. The output image does look good to me as well, but the problem is that the value of evaluation outcome doesn't look good when I use evaluate_kitty.py.
I haven't train the model for myself, so I used the pretrained model you provided. I got error too when I try to use --spilt eigen; therefore, I only test on split kitti.
This is exactly what I have typed:
$python utils/evaluate_kitti.py --split kitti --predicted_disp_path ~/Downloads/datasets/self/data_scene_flow_test/000005_10_disp.npy --gt_path ~/Downloads/datasets/KITTI/data_scene_flow/

About the GPU problem, I have already tried to reinstall Tensorflow.
Right now it works fine; however, at the very first time, it didn't crash either.

**Comment by keishatsai** [comment]
When I run the program, it still crashes after I reinstall Tensorflow

**Comment by mrharicot** [comment]
Hi,
The evaluation code expects more than one image I believe, which is probably why it fails.
As for why your results are different with the eigen split, is because you need to use `--garg_crop` to match the paper results.

**Comment by keishatsai** [comment]
Thank you, @mrharicot ,

I got the same error message after I added "garg_crop". Is there anything wrong with my command?
$python utils/evaluate_kitti.py --split eigen --garg_crop --predicted_disp_path ~/Downloads/datasets/self/data_scene_flow_test/000005_10_disp.npy --gt_path ~/Downloads/datasets/KITTI/

output::
0 files missing
Traceback (most recent call last):
  File "utils/evaluate_kitti.py", line 40, in <module>
    disp_pred = cv2.resize(pred_disparities[t_id], (im_sizes[t_id][1], im_sizes[t_id][0]), interpolation=cv2.INTER_LINEAR)
IndexError: index 256 is out of bounds for axis 0 with size 256

---------

About your opinion on evaluation code, I think that I understand what were you saying. I used it for one image evaluation, but this code is for model evaluation, am I right?  I was expecting that this code could help me to calculate the prediction result by using RMSE(or other measurements) because I just don't have a clue to compare two image files with different visualisations (sparse groundtruth and prediction depth).

**Comment by mrharicot** [comment]
Hi,
The evaluation code is meant to be used on the output of monodepth_main.py in test mode which should output either 200 or 697 disparities (kitti or eigen split).
You cannot use it with the output of monodepth_simple

**Comment by keishatsai** [comment]
Hey, I think that I understand what you were saying this time.
I have to use the output of test mode of monodepth_main.py, but according to the readme file, it depicts that the checkpoint model should be model-181250 which might be the model I have to trained on my own by using monodepth_main.py in train mode. Am I right? If so, is it possible that I can use the pretrained model you provided to do on the test mode? Like model_kitti or model_city2kitti?

Thank you~~

**Comment by mrharicot** [comment]
Hi,
As you can see from the readme, the pretrained models can be used on the test mode.
model_kitti or model_city2kitti are to be used on the kitti split, the eigen ones on the eigen split.

**Comment by keishatsai** [comment]
Thank you for the great help :)
