### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by MollyAmy** [mrharicot/monodepth#94]
Hello ,
I want to know if I want to change the image size 1280*720  for training data.
I need to change the monodepth/monodepth_main.py 

35 parser.add_argument('--input_height',              type=int,   help='input height', default=720)
36 parser.add_argument('--input_width',               type=int,   help='input width', default=1280)

Any code  needs to be modified ? like monodepth_model.py ?

And when I test my image using monodepth_simple.py.
Download model :  "model_cityscapes_resnet"

if the image size sets 512*256
the output like this
![2502_disp](https://user-images.githubusercontent.com/29377877/34753629-004fae42-f5f4-11e7-8197-aca4265f23e8.png)

if I change the image size 
the output like this
![2502_disp](https://user-images.githubusercontent.com/29377877/34753639-0de7f186-f5f4-11e7-878e-cdaf1acf61fa.png)

It seems that using the same model and only change the image size will affect the predicted disparity map?
Thank you.

**Comment by mrharicot** [comment]
Hi,
The model was trained for 256x512, anything different than that will confuse it.

**Comment by MollyAmy** [comment]
Ok , I know .
Thank you.
