### ISSUE TITLE
Kitti depth generation

### ISSUE THREAD

**Issue by EthanZhangYi** [mrharicot/monodepth#97]
Hi, thanks for your nice work and repo.
There is one thing I do not understand in data preprocessing.
When generating kitti depth groundtruth by utils you supplied, in this line
https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L167
Why minus 1 here in function `sub2ind` ?
Thanks~

Regards

**Comment by mrharicot** [comment]
Hi,
The sub2ind function was taken from another github repo for preprocessing KITTI lidar scans if I remember correctly.
