### ISSUE TITLE
Weird Pictures Output after Linear Interpolation by using evaluate_kitti.py

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#99]
Hello,
I was trying to enable the linear interpolation in the "evaluate_kitti.py", and saving the output of the groundtruth images.

These is what I got , does it looks correct to you?
from /2011_09_28/2011_09_28_0002_sync/velodyne_points/data/0000000012.bin
![0000000012 bin](https://user-images.githubusercontent.com/8175070/35085728-e6b755e4-fc64-11e7-84b2-1d25a0c708d3.png)
In case you need the original image
![0000000012](https://user-images.githubusercontent.com/8175070/35085835-4bb9e1f0-fc65-11e7-92fc-55ff91448f0f.jpg)
Just want to make sure that I am on the right track.
Thanks

**Comment by mrharicot** [comment]
Hi,
This is indeed correct!
You should really only use the interpolation for visualization, not for measuring errors.

**Comment by keishatsai** [comment]
Thanks for your reminder, @mrharicot .
This is indeed for visualisation only.

**Comment by keishatsai** [comment]
Hello, just realise that I didn't consider the focal length and baseline before visualising it.
```
depth_interp = lin_interp(im_shape, velo_pts_im)
flen, bline = get_focal_length_baseline(calib_dir, cam)
velo_pts_im2 = (bline * flen) / depth_interp
velo_pts_im2[np.isinf(velo_pts_im2)] = 0
plt.imsave(velo_file_name + '.png', velo_pts_im2, cmap='plasma')
```
Could you help me to check again?
I think images are more fragile.
![0000000340 bin](https://user-images.githubusercontent.com/8175070/35136775-77c4ce7a-fd20-11e7-837b-6020cb777604.png)
![0000000128 bin](https://user-images.githubusercontent.com/8175070/35136780-89bc72c2-fd20-11e7-8c6b-58bfc82401f5.png)

**Comment by keishatsai** [comment]
I simply close this issue since this has been solved. Thanks.
